"""
Translate 4CAT Zeeschuimer-import datasource `map_item` functions from Python
to JavaScript and splice them into the corresponding Zeeschuimer
`modules/<platform>.js` file.

Designed to be invoked by a GitHub Action whenever a Zeeschuimer datasource's
Python file changes on master. Can also be run locally for testing or via
`workflow_dispatch` with `--bootstrap` to translate every datasource at once.

The LLM produces only the new `map_item` function (plus any imports/helpers it
needs and free-text commentary). This script does the file integration: it
locates a marker block in the existing JS module and replaces its contents,
preserving every hand-written line outside the markers.

Usage:
    PROVIDER_API_KEY=... python helper-scripts/map_item_converter.py \\
        --files datasources/tiktok/search_tiktok.py \\
        --zeeschuimer-checkout ../zeeschuimer \\
        --output-manifest /tmp/manifest.json
"""
from __future__ import annotations

import argparse
import ast
import json
import os
import re
import sys
import time
import traceback
from pathlib import Path
from typing import Optional, TYPE_CHECKING

sys.path.insert(0, os.path.join(os.path.abspath(os.path.dirname(__file__)), "../.."))

# NOTE: `common.lib.llm.LLMAdapter` (and the langchain stack it pulls in) is
# imported lazily inside main(), not at module load. That keeps the pure
# helpers here — path derivation, splicing, linting — importable for unit
# tests without the heavy LLM dependencies installed. `from __future__ import
# annotations` makes the `LLMAdapter` type hints below strings, so they don't
# need the import at definition time either.
if TYPE_CHECKING:
    # Resolved only by type checkers / linters (never at runtime), so the
    # `llm: LLMAdapter` annotations below have a defined name without forcing
    # the langchain import.
    from common.lib.llm.adapter import LLMAdapter

# Sibling module — lives next to this script in helper-scripts/. Python adds the
# script's directory to sys.path automatically when the file is run directly.
from rules import RULES, get_regex_lint_rules


# 4CAT datasource path -> Zeeschuimer module path is derived by convention:
# the Python file is `datasources/<dir>/search_<name>.py`; the JS module is
# `modules/<name-with-hyphens>.js`. The convention only depends on the Python
# *filename*, not the directory, so cases where they differ still work
# (e.g. `xiaohongshu/search_rednote.py` -> `modules/rednote.js`,
#  `twitter-import/search_twitter.py` -> `modules/twitter.js`).
#
# Datasources without a matching Zeeschuimer module (today: facebook) are
# skipped automatically — the JS file existence check in `translate_one`
# handles them without any explicit allow-list. New Zeeschuimer datasources
# added to 4CAT are picked up automatically as long as Zeeschuimer ships the
# matching `modules/<name>.js` file.
def python_to_js_module(python_rel: str) -> Optional[str]:
    """
    Derive the Zeeschuimer module path for a 4CAT datasource Python file.
    Returns None if the path doesn't follow `datasources/<dir>/search_*.py`.
    """
    parts = python_rel.split("/")
    if len(parts) != 3 or parts[0] != "datasources":
        return None
    filename = parts[2]
    if not filename.startswith("search_") or not filename.endswith(".py"):
        return None
    base = filename[len("search_"):-len(".py")]
    if not base:
        return None
    return f"modules/{base.replace('_', '-')}.js"

DEFAULT_LLM_PROVIDER = "ollama"
DEFAULT_BASE_URL = "https://ollama.digitalmethods.net"
DEFAULT_MODEL = "qwen2.5-coder:14b"

IMPORTS_MARKER_START = "// === auto-generated imports for map_item — BLOCK REPLACED AUTOMATICALLY ==="
IMPORTS_MARKER_END = "// === end auto-generated imports ==="
BLOCK_MARKER_START = "// === auto-generated by 4cat map_item sync — BLOCK REPLACED AUTOMATICALLY ==="
BLOCK_MARKER_END = "// === end auto-generated ==="

LLM_SCHEMA = {
    "title": "MapItemTranslation",
    "type": "object",
    "required": ["map_item_function", "imports_to_add", "helpers_to_add", "commentary"],
    "properties": {
        "map_item_function": {
            "type": "string",
            "description": (
                "Full JavaScript source of the new map_item function. Must include "
                "the function declaration (e.g. 'export function map_item(item) {...}'). "
                "Do not include surrounding code from the module."
            ),
        },
        "imports_to_add": {
            "type": "array",
            "items": {"type": "string"},
            "description": (
                "Complete ES-module import statements that map_item needs. "
                "Normally empty: Zeeschuimer's `js/lib.js` (which provides MappedItem, "
                "MissingMappedField, normalize_url_encoding, strip_tags) is loaded as a "
                "plain script, NOT an ES module — its declarations are already global, "
                "so do not write `import { X } from '../js/lib.js'`. Only populate this "
                "if you genuinely need to import from another ES module."
            ),
        },
        "helpers_to_add": {
            "type": "array",
            "items": {"type": "string"},
            "description": (
                "Full source of any helper functions map_item depends on (e.g. a JS "
                "port of normalize_url_encoding). Empty array if none needed."
            ),
        },
        "commentary": {
            "type": "string",
            "description": (
                "Notes for the human reviewer: assumptions made, fields you were "
                "unsure about, Python idioms that don't translate cleanly. Plain text."
            ),
        },
    },
}

SYSTEM_PROMPT = (
    "You translate 4CAT Python `map_item` functions into JavaScript for the "
    "Zeeschuimer browser extension. You return ONLY the new map_item function, "
    "any imports it needs, any helper functions it depends on, and commentary "
    "for the human reviewer. You NEVER return the surrounding module file. "
    "You preserve the field names produced by the Python function exactly. "
    "You do not invent fields not present in the Python output. "
    "You output raw JavaScript source — never wrap it in markdown code fences "
    "(```js, ```javascript, etc.). The fields in your structured response are "
    "already typed as code; fences make them invalid."
)


# Whitelist of helpers that Zeeschuimer makes available as globals at runtime.
# `js/lib.js` is loaded as a plain <script>, not as an ES module, so its top-
# level declarations are global — they must NOT be imported. Anything not on
# this list must be inlined or added to `helpers_to_add`. Update this list
# whenever new helpers are added to `js/lib.js`.
AVAILABLE_JS_HELPERS = [
    {
        "name": "MappedItem",
        "kind": "class",
        "usage": "new MappedItem({field: value, ...})",
        "note": "Wraps the return value of map_item. Always instantiate with `new`.",
    },
    {
        "name": "MissingMappedField",
        "kind": "class",
        "usage": "new MissingMappedField(value, label)",
        "note": "Represents a field that may legitimately be missing. Always instantiate with `new`.",
    },
    {
        "name": "normalize_url_encoding",
        "kind": "function",
        "usage": "normalize_url_encoding(url)",
        "note": "Direct port of the Python helper of the same name.",
    },
    {
        "name": "strip_tags",
        "kind": "function",
        "usage": "strip_tags(html, convertNewlines = true)",
        "note": "Direct port of the Python helper of the same name.",
    },
    {
        "name": "formatUtcTimestamp",
        "kind": "function",
        "usage": "formatUtcTimestamp(timestamp)",
        "note": "Formats a UTC timestamp as a readable string.",
    },
    {
        "name": "MapItemException",
        "kind": "class",
        "usage": "throw new MapItemException(message)",
        "note": (
            "Mirror of 4CAT's `MapItemException`. Throw from `map_item` to "
            "signal a known mapping failure (e.g. unrecognized item shape); "
            "callers catch it, skip the item, and warn that the platform's "
            "format may have shifted. Always instantiate with `new`."
        ),
    },
]


def _format_available_helpers() -> str:
    lines = []
    for h in AVAILABLE_JS_HELPERS:
        lines.append(
            f"- `{h['name']}` ({h['kind']}, global) — {h['note']} "
            f"Usage: `{h['usage']}`."
        )
    return "\n".join(lines)


def _format_past_errors(rules) -> str:
    """
    Render rule records as a bulleted block for the "things to get right"
    prompt section. Each rule emits one bullet with its `prompt_rule`, plus
    optional `Wrong:` / `Right:` example lines. Multi-line examples are
    indented as code blocks.
    """
    lines = []
    for rule in rules:
        lines.append(f"- **{rule.id}** — {rule.prompt_rule}")
        for label, snippet in (("Wrong", rule.bad), ("Right", rule.good)):
            if not snippet:
                continue
            if "\n" in snippet:
                lines.append(f"    {label}:")
                lines.extend(f"        {line}" for line in snippet.split("\n"))
            else:
                lines.append(f"    {label}: `{snippet}`")
    return "\n".join(lines)


def _format_verification_checklist(rules) -> str:
    items = [r.verify for r in rules if r.verify]
    return "\n".join(f"{i + 1}. {item}" for i, item in enumerate(items))


def is_zeeschuimer_datasource(python_path: Path) -> bool:
    """
    Returns True if the given Python file defines a 4CAT Search subclass with
    `is_from_zeeschuimer = True` as a class attribute.
    """
    try:
        tree = ast.parse(python_path.read_text(encoding="utf-8"))
    except (SyntaxError, OSError):
        return False

    for node in ast.walk(tree):
        if not isinstance(node, ast.ClassDef):
            continue
        for stmt in node.body:
            if not isinstance(stmt, ast.Assign):
                continue
            for target in stmt.targets:
                if isinstance(target, ast.Name) and target.id == "is_from_zeeschuimer":
                    if isinstance(stmt.value, ast.Constant) and stmt.value.value is True:
                        return True
    return False


def discover_bootstrap_files(repo_root: Path, zeeschuimer_root: Path) -> list[Path]:
    """
    Find every Python datasource that has a matching Zeeschuimer module.
    Scans `datasources/*/search_*.py`, keeping only Zeeschuimer datasources
    whose derived JS module exists in the checkout (so e.g. facebook, which
    4CAT supports but Zeeschuimer does not, is silently dropped).
    """
    found = []
    for path in sorted((repo_root / "datasources").glob("*/search_*.py")):
        if not is_zeeschuimer_datasource(path):
            continue
        rel = path.relative_to(repo_root).as_posix()
        js_rel = python_to_js_module(rel)
        if not js_rel:
            continue
        if (zeeschuimer_root / js_rel).exists():
            found.append(path)
    return found


def build_user_prompt(python_source: str, existing_module_source: str, python_rel: str) -> str:
    helpers_block = _format_available_helpers()
    past_errors_block = _format_past_errors(RULES)
    verification_block = _format_verification_checklist(RULES)
    return (
        f"# Source Python file (datasources/{python_rel})\n"
        "This is the file that just changed in 4CAT. The `map_item` function on the "
        "class is the source of truth — your JavaScript translation must produce an "
        "object with the same field names and equivalent values.\n\n"
        f"```python\n{python_source}\n```\n\n"
        "# Existing Zeeschuimer module\n"
        "This module's `capture()` function returns the raw items that will be "
        "passed to `map_item(item)` as `item`. Use it to understand the input shape "
        "and to match the existing code style (ES modules, `export` keyword, etc.).\n\n"
        f"```javascript\n{existing_module_source}\n```\n\n"
        "# Available Zeeschuimer JS helpers (globals)\n"
        "Zeeschuimer loads `js/lib.js` as a plain `<script>`, NOT as an ES "
        "module. Its top-level declarations are global — available everywhere "
        "without any `import`. Use them by name only. The following are the "
        "helpers you may use; everything else must be implemented as JavaScript "
        "(inline in `map_item_function` or as separate snippets in `helpers_to_add`).\n\n"
        f"{helpers_block}\n\n"
        "# Imports — almost always none\n"
        "Do NOT write `import { MappedItem } from '../js/lib.js'` or any similar "
        "statement for the helpers above — `lib.js` is a script, not a module, "
        "and the import will fail at runtime. The `imports_to_add` field should "
        "normally be EMPTY; only include an import if you genuinely need to pull "
        "from another ES module (rare for `map_item`).\n\n"
        "Also forbidden, because they don't exist in JavaScript:\n"
        "- Anything from `common.lib.helpers` not listed above (e.g. `convert_to_int`, `timify`)\n"
        "- Anything from `common.lib.exceptions`, `common.lib.user_input`, `backend.lib.*`\n"
        "- Python stdlib modules (`datetime`, `urllib.parse`, `re`, `json`, `hashlib`, etc.) — use the JavaScript native equivalents instead.\n\n"
        "# Things to get right — past errors from this generator\n"
        "Each item below has been observed in previous LLM output. The script lints "
        "for many of them and surfaces matches as warnings on the PR. Translate accordingly.\n\n"
        f"{past_errors_block}\n\n"
        "# Before submitting, verify your output\n"
        f"{verification_block}\n\n"
        "# Output format\n"
        "Use `export function map_item(item) { ... }` to match this module's ES-module style. "
        "Return raw JavaScript source — do NOT wrap fields in markdown code fences. "
        "The `imports_to_add` field is normally an empty array (the helpers above are global, not imported). "
        "The `helpers_to_add` field should contain full helper-function source (each entry one complete function)."
    )


# Remove these code fences that keep appearing in the LLM output, even when explicitly told not to use them.
_FENCE_OPEN = re.compile(r"^```(?:js|javascript|typescript|ts)?\s*\n?", re.IGNORECASE)
_FENCE_CLOSE = re.compile(r"\n?```\s*$")


def strip_code_fences(s: str) -> str:
    """
    Strip leading/trailing markdown code fences (```js, ```javascript, ``` etc.)
    Idempotent; returns the input unchanged if no fences found. Defensive
    post-processing because LLMs frequently wrap their answers in fences even
    when explicitly told not to.
    """
    if not s:
        return s
    s = s.strip()
    s = _FENCE_OPEN.sub("", s)
    s = _FENCE_CLOSE.sub("", s)
    return s.strip()


# Helper to check for common issues
def _strip_js_comments(s: str) -> str:
    """
    Remove `//` line comments and `/* */` block comments so they don't trip the
    pattern checks, while preserving the contents of string and template
    literals. A naive `re.sub(r"//[^\n]*", "", s)` would eat the `//` in a URL
    like `"https://example.com"` and mangle the string, producing bogus lint
    warnings (e.g. spurious "literal newline in string").

    A small scanner tracks string state. It deliberately does NOT try to
    distinguish a regex literal from division — `/` is only acted on when it
    begins `//` or `/*`, neither of which is a valid start to a regex literal
    in practice (an empty regex is written `/(?:)/`).
    """
    out = []
    i, n = 0, len(s)
    quote = None  # active string delimiter: ' " or `
    while i < n:
        c = s[i]
        if quote is not None:
            out.append(c)
            if c == "\\" and i + 1 < n:  # escape: copy the next char verbatim
                out.append(s[i + 1])
                i += 2
                continue
            if c == quote:
                quote = None
            i += 1
            continue
        if c in ("'", '"', "`"):
            quote = c
            out.append(c)
            i += 1
            continue
        if c == "/" and i + 1 < n and s[i + 1] == "/":
            i += 2
            while i < n and s[i] != "\n":
                i += 1
            continue
        if c == "/" and i + 1 < n and s[i + 1] == "*":
            i += 2
            while i + 1 < n and not (s[i] == "*" and s[i + 1] == "/"):
                i += 1
            i += 2  # skip the closing */
            continue
        out.append(c)
        i += 1
    return "".join(out)


# Regex checks for known anti-patterns. Sourced from the rule registry so
# that prompt guidance and lint stay in sync. Bespoke checks below (class
# instantiation, literal newlines, regex use) are not in the registry's
# regex list — they're tied to records by `id`.
LINT_PATTERNS = get_regex_lint_rules()


# Lexer that matches JS string and template literals as whole units. Used to
# check whether a single- or double-quoted literal contains a raw newline (a
# JS syntax error). Template literals are allowed to span lines so they're
# matched and skipped. Regex matches escapes (\\.) so embedded `\"` etc. don't
# prematurely close the string.
_JS_STRING_LITERAL = re.compile(
    r'''
        (?P<dq>"(?:[^"\\]|\\.)*")
      | (?P<sq>'(?:[^'\\]|\\.)*')
      | (?P<tl>`(?:[^`\\]|\\.)*`)
    ''',
    re.DOTALL | re.VERBOSE,
)


def _has_literal_newline_in_string(source: str) -> bool:
    for m in _JS_STRING_LITERAL.finditer(source):
        if m.group("tl"):
            continue  # template literals legally span lines
        if "\n" in m.group(0):
            return True
    return False


# Heuristic openers for a regex literal: `.match(/`, `new RegExp(/`, etc.
# Scoped to method-call contexts because regex `/` is hard to disambiguate
# from division otherwise. False negatives are acceptable; false positives
# would block valid code.
_REGEX_LITERAL_OPENER = re.compile(
    r"(?:\.(?:match|replace|replaceAll|split|search|matchAll|test|exec)\s*\(\s*"
    r"|\bnew\s+RegExp\s*\(\s*)/"
)


def _uses_regex(source: str) -> bool:
    """
    Detect whether the source uses a regex in a recognized context
    (`.match(/.../)`, `new RegExp(...)`, etc.). Current models translate
    regex unreliably — this is a blanket "needs human review" flag, not a
    bug detector. Reviewer must verify the regex behavior end-to-end.
    """
    return bool(_REGEX_LITERAL_OPENER.search(source))


def lint_translation(translation: dict) -> list:
    """
    Scan the generated JS for known bugs. Returns a list of error strings
    (empty if clean). Runs on `map_item_function` and each `helpers_to_add`
    entry. Comments are stripped before scanning to avoid false positives
    on commentary text.
    """
    issues = []
    sources = []
    fn = translation.get("map_item_function") or ""
    if fn:
        sources.append(("map_item_function", fn))
    for i, h in enumerate(translation.get("helpers_to_add") or []):
        if isinstance(h, str) and h:
            sources.append((f"helpers_to_add[{i}]", h))

    for label, source in sources:
        clean = _strip_js_comments(source)

        seen = set()
        for regex, message in LINT_PATTERNS:
            if regex.search(clean) and message not in seen:
                issues.append(f"[{label}] {message}")
                seen.add(message)

        # Class instantiation without `new` (variable-width lookbehind, so
        # check the chars before each match manually).
        for cls in ("MappedItem", "MissingMappedField", "MapItemException"):
            pattern = re.compile(rf"\b{cls}\s*\(")
            reported = False
            for m in pattern.finditer(clean):
                before = clean[max(0, m.start() - 8) : m.start()]
                if not re.search(r"\bnew\s+$", before):
                    if not reported:
                        issues.append(
                            f"[{label}] `{cls}` instantiated without `new` keyword "
                            f"(at offset {m.start()}). All class instantiations need `new`."
                        )
                        reported = True

        # Literal newlines inside single- or double-quoted strings (a JS
        # syntax error). The LLM sometimes emits e.g. `.join('\n')` as
        # `.join('<actual newline>')` which doesn't parse.
        if _has_literal_newline_in_string(clean):
            issues.append(
                f"[{label}] Literal newline inside a string literal — JS strings "
                f"can't span lines without escape (`\"\\n\"`) or template literals "
                f"(`` `\\n` ``)."
            )

        # Regex translation is unreliable on the current model — flag any
        # regex use for manual reviewer verification rather than trying to
        # detect specific failure modes (literal newlines, dropped escapes,
        # flag-syntax differences, character-class drift). The reviewer is
        # the source of truth here until we can upgrade the model.
        if _uses_regex(clean):
            issues.append(
                f"[{label}] Regex detected. The current LLM translates regex "
                f"unreliably (escapes, character classes, flags) — please verify "
                f"the regex behavior against the Python original by hand."
            )

    return issues


def validate_translation(translation: dict) -> Optional[str]:
    """
    Returns None if the translation passes basic sanity checks, else a string
    describing what went wrong.
    """
    # `or ""` not a default: structured output can yield an explicit null for a
    # required field, and `None.strip()` would raise instead of being reported.
    fn = (translation.get("map_item_function") or "").strip()
    if not fn:
        return "LLM returned empty map_item_function"
    if not re.search(r"\bmap_item\b", fn):
        return "LLM output does not contain `map_item` identifier"
    if not re.search(r"function\s+map_item|map_item\s*=|map_item\s*:", fn):
        return "LLM output does not declare `map_item` as a function"
    return None


# A pre-existing top-level `map_item` declaration. Used on the first sync (no
# markers yet) to refuse appending a SECOND declaration, which would be a JS
# redeclaration error. Conservative: matches only real declaration forms
# (`function map_item`, `const/let/var map_item =`), not incidental mentions;
# comments are stripped before this is applied.
_PREEXISTING_MAP_ITEM_RE = re.compile(
    r"(?:export\s+)?(?:async\s+)?function\s+map_item\b"
    r"|(?:export\s+)?(?:const|let|var)\s+map_item\s*="
)


def splice_into_module(existing: str, translation: dict, python_rel: str) -> str:
    """
    Insert / replace the auto-generated marker blocks in the JS
    module text.

    Raises ValueError if exactly one of (start, end) markers is present —
    that means the file is corrupted or partially hand-edited and we should
    refuse to touch it. Also raises ValueError on the first sync (no markers
    yet) if the module already defines its own `map_item`, since appending a
    second declaration would not parse.
    """
    main_block_body = []
    for helper in translation.get("helpers_to_add", []):
        helper = helper.strip()
        if helper:
            main_block_body.append(helper)
    fn = translation["map_item_function"].strip()
    main_block_body.append(fn)
    main_block = (
        f"{BLOCK_MARKER_START}\n"
        f"// (regenerated from {python_rel})\n"
        + "\n\n".join(main_block_body)
        + f"\n{BLOCK_MARKER_END}\n"
    )

    imports = [imp.strip() for imp in translation.get("imports_to_add", []) if imp.strip()]
    # Drop imports that already appear verbatim outside the marker block.
    existing_outside_block = re.sub(
        re.escape(BLOCK_MARKER_START) + r".*?" + re.escape(BLOCK_MARKER_END) + r"\n?",
        "",
        existing,
        flags=re.DOTALL,
    )
    existing_outside_imports_block = re.sub(
        re.escape(IMPORTS_MARKER_START) + r".*?" + re.escape(IMPORTS_MARKER_END) + r"\n?",
        "",
        existing_outside_block,
        flags=re.DOTALL,
    )
    imports = [imp for imp in imports if imp not in existing_outside_imports_block]

    imports_block = ""
    if imports:
        imports_block = (
            f"{IMPORTS_MARKER_START}\n"
            + "\n".join(imports)
            + f"\n{IMPORTS_MARKER_END}\n"
        )

    updated = existing

    # Replace or insert imports block.
    has_imports_start = IMPORTS_MARKER_START in updated
    has_imports_end = IMPORTS_MARKER_END in updated
    if has_imports_start ^ has_imports_end:
        raise ValueError(
            "Auto-generated imports markers are partially missing in the existing "
            "module — refusing to overwrite. Restore both markers or remove both."
        )
    if has_imports_start and has_imports_end:
        # Replacement is a callable, NOT a string: a string replacement runs
        # through re's escape processing, so backslashes in the generated JS
        # (regex literals like `/\w+/`, `"\n"` escapes, `\g<...>`) would be
        # corrupted or raise `re.error`. A callable's return value is inserted
        # verbatim.
        updated = re.sub(
            re.escape(IMPORTS_MARKER_START) + r".*?" + re.escape(IMPORTS_MARKER_END) + r"\n?",
            lambda _match: imports_block,
            updated,
            count=1,
            flags=re.DOTALL,
        )
    elif imports_block:
        # Prepend at top of file.
        if updated and not updated.startswith("\n"):
            updated = imports_block + "\n" + updated
        else:
            updated = imports_block + updated

    # Replace or append main block.
    has_main_start = BLOCK_MARKER_START in updated
    has_main_end = BLOCK_MARKER_END in updated
    if has_main_start ^ has_main_end:
        raise ValueError(
            "Auto-generated map_item markers are partially missing in the existing "
            "module — refusing to overwrite. Restore both markers or remove both."
        )
    if has_main_start and has_main_end:
        # Callable replacement (see note on the imports block above): the
        # generated JS routinely contains `\w`/`\d` regex escapes and `"\n"`
        # string escapes, which a string replacement would either mangle into
        # a raw newline or reject with `re.error: bad escape`.
        updated = re.sub(
            re.escape(BLOCK_MARKER_START) + r".*?" + re.escape(BLOCK_MARKER_END) + r"\n?",
            lambda _match: main_block,
            updated,
            count=1,
            flags=re.DOTALL,
        )
    else:
        # First sync for this module (no markers yet): appending is only safe if
        # the module doesn't already declare its own `map_item`. Two declarations
        # would be a JS redeclaration error. Strip comments first so a commented-
        # out or merely-referenced `map_item` doesn't trip the check.
        if _PREEXISTING_MAP_ITEM_RE.search(_strip_js_comments(updated)):
            raise ValueError(
                "Module already defines `map_item` outside the auto-generated "
                f"markers. Wrap that function in the `{BLOCK_MARKER_START}` / "
                f"`{BLOCK_MARKER_END}` markers (or remove it) so the sync can "
                "replace it in place — refusing to append a second declaration."
            )
        if not updated.endswith("\n"):
            updated += "\n"
        updated += "\n" + main_block

    return updated


def extract_raw_from_exception(exc: BaseException) -> Optional[str]:
    """
    Pull whatever raw LLM output we can find off a LangChain exception. Tries
    several attribute names since they vary by LangChain version. Returns None
    if nothing recoverable.
    """
    for attr in ("llm_output", "observation", "output"):
        val = getattr(exc, attr, None)
        if isinstance(val, str):
            return val
    return None


def describe_raw(raw) -> Optional[dict]:
    """
    Summarize the raw AIMessage from an `include_raw=True` structured-output call
    so a failed (or surprising) translation is diagnosable from CI logs alone,
    even when the JSON manifest artifact is lost.

    The key signal is `finish_reason`: "length" means the model was truncated
    mid-output (raise --max-tokens); "stop" with empty `content` but a populated
    reasoning channel means a reasoning model put its answer where the
    structured-output parser can't see it (a structured-output *method* problem,
    not a token-budget one).
    """
    if raw is None:
        return None
    meta = getattr(raw, "response_metadata", {}) or {}
    addl = getattr(raw, "additional_kwargs", {}) or {}
    content = getattr(raw, "content", "") or ""
    if not isinstance(content, str):
        content = str(content)
    # Reasoning models surface their analysis channel under varying keys
    # depending on provider/proxy; check the common ones.
    reasoning = (
        addl.get("reasoning_content")
        or addl.get("reasoning")
        or meta.get("reasoning_content")
        or ""
    )
    if not isinstance(reasoning, str):
        reasoning = str(reasoning)
    return {
        "finish_reason": meta.get("finish_reason"),
        "content_chars": len(content),
        "reasoning_chars": len(reasoning),
        "token_usage": meta.get("token_usage") or meta.get("usage"),
        "content_preview": content[:500],
        "reasoning_preview": reasoning[:500],
    }


def format_raw_summary(d: dict) -> str:
    """One-line, CI-log-friendly rendering of describe_raw()."""
    return (
        f"finish_reason={d.get('finish_reason')!r} "
        f"content_chars={d.get('content_chars')} "
        f"reasoning_chars={d.get('reasoning_chars')} "
        f"token_usage={d.get('token_usage')}"
    )


def build_json_format_instructions(schema: dict) -> str:
    """
    Render an LLM_SCHEMA-shaped JSON schema into prompt instructions, for
    `prompt` output mode where no response_format is sent. Single source of
    truth stays the schema: keys, types, and descriptions all come from it.
    """
    props = schema.get("properties", {})
    required = schema.get("required", list(props))
    field_lines = []
    shape_lines = []
    for key in required:
        spec = props.get(key, {})
        typ = spec.get("type", "string")
        desc = " ".join(spec.get("description", "").split())
        field_lines.append(f'- "{key}" ({typ}): {desc}'.rstrip())
        shape_lines.append(f'  "{key}": <{typ}>')
    return (
        "Respond with ONLY a single JSON object — no markdown, no ``` code "
        "fences, no prose before or after it. The object must have exactly "
        "these keys:\n"
        + "\n".join(field_lines)
        + "\n\nShape:\n{\n"
        + ",\n".join(shape_lines)
        + "\n}\n\n"
        "String values must be valid JSON strings (escape newlines as \\n, "
        "quotes as \\\"). Array values must be JSON arrays of strings (use [] "
        "when empty)."
    )


def parse_json_object(text: str) -> Optional[dict]:
    """
    Pull a JSON object out of a model reply in `prompt` output mode. Tries the
    whole (fence-stripped) text first, then falls back to the first balanced
    {...} span. Returns None if nothing parses to a dict.
    """
    if not text:
        return None
    candidate = strip_code_fences(text).strip()
    for attempt in (candidate, _first_brace_span(candidate)):
        if not attempt:
            continue
        try:
            parsed = json.loads(attempt)
        except (ValueError, TypeError):
            continue
        if isinstance(parsed, dict):
            return parsed
    return None


def _first_brace_span(text: str) -> Optional[str]:
    """Return the first balanced {...} substring, or None. Brace-depth scan that
    ignores braces inside JSON string literals (respecting backslash escapes)."""
    start = text.find("{")
    if start == -1:
        return None
    depth = 0
    in_string = False
    escaped = False
    for i in range(start, len(text)):
        ch = text[i]
        if in_string:
            if escaped:
                escaped = False
            elif ch == "\\":
                escaped = True
            elif ch == '"':
                in_string = False
            continue
        if ch == '"':
            in_string = True
        elif ch == "{":
            depth += 1
        elif ch == "}":
            depth -= 1
            if depth == 0:
                return text[start:i + 1]
    return None


def translate_one(
    llm: LLMAdapter,
    python_path: Path,
    repo_root: Path,
    zeeschuimer_root: Path,
    strict_lint: bool,
    structured: bool = True,
) -> dict:
    """
    Translate one Python file. Returns a manifest entry dict.

    :param structured: When True (default), the schema was bound via
        `set_structure` and the model returns a parsed dict. When False
        (prompt mode), we ask for JSON in the prompt and parse the reply text
        ourselves — for models/proxies whose response_format is broken.
    """
    rel = python_path.relative_to(repo_root).as_posix()
    entry = {
        "python_file": rel,
        "js_file": None,
        "status": "failed",
        "commentary": "",
        "duration_seconds": None,
        "raw_response": None,
        "lint_warnings": [],
        "translation": None,
        "error": None,
    }

    if not is_zeeschuimer_datasource(python_path):
        entry["status"] = "skipped"
        entry["error"] = "not a Zeeschuimer datasource (is_from_zeeschuimer != True)"
        return entry

    js_rel = python_to_js_module(rel)
    if not js_rel:
        entry["status"] = "skipped"
        entry["error"] = f"could not derive Zeeschuimer module path from {rel} (expected `datasources/<dir>/search_*.py` form)"
        return entry
    entry["js_file"] = js_rel

    js_path = zeeschuimer_root / js_rel
    if not js_path.exists():
        entry["status"] = "skipped"
        entry["error"] = f"Zeeschuimer module {js_rel} does not exist in checkout"
        return entry

    python_source = python_path.read_text(encoding="utf-8")
    existing_module = js_path.read_text(encoding="utf-8")
    user_prompt = build_user_prompt(python_source, existing_module, rel)
    # Prompt mode: no response_format is sent, so spell out the JSON contract in
    # the prompt itself and parse the reply text ourselves below.
    if not structured:
        user_prompt = user_prompt + "\n\n" + build_json_format_instructions(LLM_SCHEMA)

    started = time.monotonic()
    raw_response: Optional[str] = None
    translation: Optional[dict] = None
    llm_error: Optional[str] = None
    diagnostics: Optional[dict] = None

    try:
        response = llm.generate_text(user_prompt, system_prompt=SYSTEM_PROMPT)
        if structured:
            # Structured output bound with include_raw=True (see set_structure in
            # main()): `generate_text` returns a {"raw", "parsed",
            # "parsing_error"} wrapper instead of raising on a parse failure, so
            # we can record *why* a translation failed (see describe_raw) rather
            # than getting an opaque "Invalid json output:" with an empty payload.
            if isinstance(response, dict) and "raw" in response and "parsed" in response:
                diagnostics = describe_raw(response.get("raw"))
                parsed = response.get("parsed")
                parse_err = response.get("parsing_error")
                if parsed is not None:
                    translation = parsed
                else:
                    detail = f": {parse_err}" if parse_err else ""
                    llm_error = f"structured output not parseable{detail}"
            elif isinstance(response, dict):
                translation = response
            else:
                llm_error = (
                    f"Expected dict from structured output, got "
                    f"{type(response).__name__}"
                )
        else:
            # Prompt mode: `response` is a plain AIMessage. Capture diagnostics
            # off it, then parse JSON out of its text content ourselves.
            diagnostics = describe_raw(response)
            text = response.content if isinstance(response.content, str) else str(response.content)
            raw_response = text
            translation = parse_json_object(text)
            if translation is None:
                llm_error = "could not parse a JSON object from the model reply"
    except Exception as e:
        raw_response = extract_raw_from_exception(e)
        llm_error = f"LLM call failed: {e}"

    entry["duration_seconds"] = round(time.monotonic() - started, 2)
    entry["raw_response"] = raw_response
    if diagnostics is not None:
        entry["diagnostics"] = diagnostics
        print(f"  -> {format_raw_summary(diagnostics)}", flush=True)

    if llm_error:
        entry["error"] = llm_error
        return entry
    if translation is None:
        entry["error"] = "no translation produced (no error raised, no dict returned)"
        return entry

    # Defensive: strip stray markdown code fences from the function source and
    # each helper. Models wrap things in ```js even when instructed not to.
    if isinstance(translation.get("map_item_function"), str):
        translation["map_item_function"] = strip_code_fences(translation["map_item_function"])
    helpers = translation.get("helpers_to_add")
    if isinstance(helpers, list):
        translation["helpers_to_add"] = [
            strip_code_fences(h) if isinstance(h, str) else h for h in helpers
        ]

    bad = validate_translation(translation)
    if bad:
        entry["translation"] = translation
        entry["error"] = bad
        return entry

    lint_issues = lint_translation(translation)
    if lint_issues:
        if strict_lint:
            entry["translation"] = translation
            entry["lint_warnings"] = lint_issues
            entry["error"] = "Lint issues (--strict-lint):\n  - " + "\n  - ".join(lint_issues)
            return entry
        # Non-strict (default): record as warnings and let the file ship. The
        # reviewer sees the issues in the PR body and fixes them by hand.
        entry["lint_warnings"] = lint_issues

    try:
        spliced = splice_into_module(existing_module, translation, rel)
    except ValueError as e:
        entry["translation"] = translation
        entry["error"] = str(e)
        return entry

    js_path.write_text(spliced, encoding="utf-8")
    entry["status"] = "ok"
    entry["commentary"] = translation.get("commentary", "").strip()
    # Keep parsed translation on warning entries so the PR / reviewer can see
    # exactly what was emitted alongside the warnings.
    if entry["lint_warnings"]:
        entry["translation"] = translation
    return entry


def main():
    cli = argparse.ArgumentParser(description=__doc__)
    group = cli.add_mutually_exclusive_group(required=True)
    group.add_argument("--files", nargs="+", help="Specific datasource files to translate.")
    group.add_argument(
        "--bootstrap",
        action="store_true",
        help="Translate every Zeeschuimer datasource in the repo.",
    )
    cli.add_argument(
        "--zeeschuimer-checkout",
        required=True,
        type=Path,
        help="Path to a local clone of the Zeeschuimer repo.",
    )
    cli.add_argument(
        "--output-manifest",
        required=True,
        type=Path,
        help="Where to write the JSON manifest of results.",
    )
    cli.add_argument(
        "--llm_provider",
        default=os.environ.get("LLM_PROVIDER", DEFAULT_LLM_PROVIDER),
        help=f"LLM provider to use (default: {DEFAULT_LLM_PROVIDER} or $LLM_PROVIDER).",
    )
    cli.add_argument(
        "--base_url",
        default=os.environ.get("LLM_BASE_URL", DEFAULT_BASE_URL),
        help=f"Base URL for the LLM API (default: {DEFAULT_BASE_URL}, or $LLM_BASE_URL).",
    )
    cli.add_argument(
        "--model",
        default=os.environ.get("LLM_MODEL", DEFAULT_MODEL),
        help=f"Ollama model to use (default: {DEFAULT_MODEL}, or $LLM_MODEL).",
    )
    cli.add_argument(
        "--max-tokens",
        type=int,
        default=int(os.environ.get("LLM_MAX_TOKENS", "50000")),
        help=(
            "Max output tokens (a ceiling, not a target). Reasoning models like "
            "gpt-oss spend tokens in their analysis channel before emitting the "
            "answer; too low a ceiling truncates mid-reasoning and yields empty "
            "output. Default: 50000, or $LLM_MAX_TOKENS."
        ),
    )
    cli.add_argument(
        "--output-mode",
        choices=["structured", "prompt"],
        default=os.environ.get("LLM_OUTPUT_MODE", "structured"),
        help=(
            "How JSON is requested. 'structured' (default) binds the schema via "
            "response_format / function calling — reliable on backends that "
            "support it. 'prompt' asks for JSON in the prompt and parses the "
            "reply text, for models/proxies whose response_format is broken "
            "(e.g. gpt-oss-120b on llmproxy.uva.nl, which returns null content "
            "with any response_format). Default: structured, or $LLM_OUTPUT_MODE."
        ),
    )
    cli.add_argument(
        "--no-fail-fast",
        action="store_true",
        help=(
            "Continue translating remaining files even after one fails. By "
            "default the script aborts on the first failure, since failures here "
            "are typically configuration- or model-correlated and continuing "
            "wastes LLM time."
        ),
    )
    cli.add_argument(
        "--strict-lint",
        action="store_true",
        help=(
            "Treat lint findings (Python `.get()`, missing `new`, literal newlines "
            "in strings, etc.) as failures rather than warnings. Default is "
            "warnings — the file still ships and the PR body surfaces the "
            "issues so the reviewer can fix them by hand."
        ),
    )
    args = cli.parse_args()

    provider_api_key = os.environ.get("PROVIDER_API_KEY")
    if not provider_api_key:
        sys.exit("Error: PROVIDER_API_KEY environment variable not set.")

    repo_root = Path(__file__).resolve().parent.parent

    if args.bootstrap:
        files = discover_bootstrap_files(repo_root, args.zeeschuimer_checkout.resolve())
        if not files:
            sys.exit("No Zeeschuimer datasources found to bootstrap.")
    else:
        files = [Path(f).resolve() for f in args.files]

    # Imported here (not at module top) so the pure helpers above stay
    # importable for tests without the langchain stack. See note near the
    # imports at the top of this file.
    from common.lib.llm.adapter import LLMAdapter
    base_url = args.base_url

    llm = LLMAdapter(
        model={
            "local_id": args.model,
            "wrapper": "ollama"
        },
        server={
            "url": base_url
        },
        api_key=provider_api_key,
        temperature=0.2,
        max_tokens=args.max_tokens,
        client_kwargs={"headers": {"X-API-KEY": provider_api_key}},
    )

    # Structured output (default): bind the schema so the model returns a
    # schema-validated dict — what makes splicing reliable. include_raw=True
    # gives us the raw AIMessage on failure for diagnosis. Fail fast if the
    # model/endpoint can't bind it rather than producing unparseable output.
    #
    # `prompt` mode skips this entirely: no response_format is sent, the JSON
    # contract is spelled out in the prompt, and we parse the reply text
    # ourselves. Use it for models/proxies whose response_format is broken —
    # e.g. gpt-oss-120b on llmproxy.uva.nl returns null content with any
    # response_format, but answers cleanly when just asked for JSON.
    structured = args.output_mode == "structured"
    if structured:
        try:
            llm.set_structure(LLM_SCHEMA, include_raw=True)
        except Exception as e:
            sys.exit(f"Error: could not enable structured output: {e}")

    fail_fast = not args.no_fail_fast
    print(
        f"Using model: {args.model} "
        f"(output_mode: {args.output_mode}, "
        f"fail_fast: {fail_fast}, strict_lint: {args.strict_lint})"
    )

    entries = []
    overall_started = time.monotonic()
    for python_path in files:
        rel_for_log = python_path.relative_to(repo_root).as_posix()
        print(f"Translating {rel_for_log}...", flush=True)
        per_file_started = time.monotonic()
        try:
            entry = translate_one(
                llm,
                python_path,
                repo_root,
                args.zeeschuimer_checkout.resolve(),
                args.strict_lint,
                structured=structured,
            )
        except Exception as e:
            entry = {
                "python_file": str(python_path),
                "js_file": None,
                "status": "failed",
                "commentary": "",
                "duration_seconds": round(time.monotonic() - per_file_started, 2),
                "error": f"unexpected exception: {e}\n{traceback.format_exc()}",
            }
        entry["model"] = args.model
        entries.append(entry)
        dur = entry.get("duration_seconds")
        dur_str = f" in {dur}s" if dur is not None else ""
        err_str = f" ({entry['error']})" if entry.get("error") else ""
        warn_str = (
            f" with {len(entry['lint_warnings'])} lint warning(s)"
            if entry.get("lint_warnings")
            else ""
        )
        print(f"  -> {entry['status']}{warn_str}{dur_str}{err_str}", flush=True)

        if entry["status"] == "failed" and fail_fast:
            remaining = len(files) - len(entries)
            if remaining > 0:
                print(
                    f"\nFail-fast: aborting after first failure; skipping "
                    f"{remaining} remaining file(s). Pass --no-fail-fast to continue past failures.",
                    flush=True,
                )
            break

    overall_duration = round(time.monotonic() - overall_started, 2)
    manifest = {
        "model": args.model,
        "provider": args.llm_provider,
        "output_mode": args.output_mode,
        "fail_fast": fail_fast,
        "strict_lint": args.strict_lint,
        "total_duration_seconds": overall_duration,
        "entries": entries,
    }
    args.output_manifest.parent.mkdir(parents=True, exist_ok=True)
    args.output_manifest.write_text(json.dumps(manifest, indent=2), encoding="utf-8")

    n_ok = sum(1 for e in entries if e["status"] == "ok")
    n_with_warnings = sum(1 for e in entries if e["status"] == "ok" and e.get("lint_warnings"))
    n_failed = sum(1 for e in entries if e["status"] == "failed")
    n_skipped = sum(1 for e in entries if e["status"] == "skipped")
    print(
        f"\nDone with model `{args.model}` in {overall_duration}s: "
        f"{n_ok} ok ({n_with_warnings} with warnings), "
        f"{n_failed} failed, {n_skipped} skipped."
    )
    print(f"Manifest written to {args.output_manifest}")

    if n_ok == 0 and n_failed > 0:
        sys.exit(1)


if __name__ == "__main__":
    main()
