# Copied from existing Dockerfile; likely could be greatly reduced
# but unsure what frontend actually requires at this time
FROM debian:buster

RUN apt-get update && apt install -y \
    python3-pip \
    gawk \
    curl \
    libpq-dev \
    python3-dev \
    postgresql-server-dev-all \
    unzip \
    wget \
    xvfb \
    postgresql-client \
    netcat

WORKDIR /usr/src/app

# Install dependencies that may or may not be needed
RUN pip3 install --upgrade pip
COPY ./requirements.txt /usr/src/app/requirements.txt
COPY ./setup.py /usr/src/app/setup.py
COPY ./VERSION /usr/src/app/VERSION
COPY ./README.md /usr/src/app/README.md
RUN mkdir /usr/src/app/backend
RUN mkdir /usr/src/app/webtool
RUN mkdir /usr/src/app/datasources
RUN pip3 install -r requirements.txt

# Definitely needs this though
RUN pip3 install gunicorn

# copy project
# (copy example config first, if user has own config, it will replace this)
COPY ./config.py-example /usr/src/app/config.py
COPY . /usr/src/app/

EXPOSE 5000

ENTRYPOINT exec gunicorn --worker-tmp-dir /dev/shm --workers=2 --threads=4 --worker-class=gthread --reload --bind 0.0.0.0:5000 webtool:app
