"""
Translate 4CAT Zeeschuimer-import datasource `map_item` functions from Python
to JavaScript and splice them into the corresponding Zeeschuimer
`modules/<platform>.js` file.

Designed to be invoked by a GitHub Action whenever a Zeeschuimer datasource's
Python file changes on master. Can also be run locally for testing or via
`workflow_dispatch` with `--bootstrap` to translate every datasource at once.

The LLM produces only the new `map_item` function (plus any imports/helpers it
needs and free-text commentary). This script does the file integration: it
locates a marker block in the existing JS module and replaces its contents,
preserving every hand-written line outside the markers.

Usage:
    DMI_OLLAMA_KEY=... python helper-scripts/map_item_converter.py \\
        --files datasources/tiktok/search_tiktok.py \\
        --zeeschuimer-checkout ../zeeschuimer \\
        --output-manifest /tmp/manifest.json
"""
import argparse
import ast
import json
import os
import re
import subprocess
import sys
import time
import traceback
from pathlib import Path
from typing import Optional

sys.path.insert(0, os.path.join(os.path.abspath(os.path.dirname(__file__)), ".."))

from common.lib.llm import LLMAdapter


# 4CAT datasource path -> Zeeschuimer module path (relative to checkout root).
# Verified against https://github.com/digitalmethodsinitiative/zeeschuimer/tree/master/modules
# Note: facebook has no Zeeschuimer module today, so it's intentionally absent.
PLATFORM_MAP = {
    "datasources/douyin/search_douyin.py": "modules/douyin.js",
    "datasources/gab/search_gab.py": "modules/gab.js",
    "datasources/imgur/search_imgur.py": "modules/imgur.js",
    "datasources/instagram/search_instagram.py": "modules/instagram.js",
    "datasources/linkedin/search_linkedin.py": "modules/linkedin.js",
    "datasources/ninegag/search_9gag.py": "modules/9gag.js",
    "datasources/pinterest/search_pinterest.py": "modules/pinterest.js",
    "datasources/threads/search_threads.py": "modules/threads.js",
    "datasources/tiktok/search_tiktok.py": "modules/tiktok.js",
    "datasources/tiktok_comments/search_tiktok_comments.py": "modules/tiktok-comments.js",
    "datasources/truth/search_truth.py": "modules/truth.js",
    "datasources/twitter-import/search_twitter.py": "modules/twitter.js",
    "datasources/xiaohongshu/search_rednote.py": "modules/rednote.js",
    "datasources/xiaohongshu_comments/search_rednote_comments.py": "modules/rednote-comments.js",
}

DEFAULT_MODEL = "qwen2.5-coder:14b"

IMPORTS_MARKER_START = "// === auto-generated imports for map_item — DO NOT EDIT BY HAND ==="
IMPORTS_MARKER_END = "// === end auto-generated imports ==="
BLOCK_MARKER_START = "// === auto-generated by 4cat map_item sync — DO NOT EDIT BY HAND ==="
BLOCK_MARKER_END = "// === end auto-generated ==="

LLM_SCHEMA = {
    "title": "MapItemTranslation",
    "type": "object",
    "required": ["map_item_function", "imports_to_add", "helpers_to_add", "commentary"],
    "properties": {
        "map_item_function": {
            "type": "string",
            "description": (
                "Full JavaScript source of the new map_item function. Must include "
                "the function declaration (e.g. 'export function map_item(item) {...}'). "
                "Do not include surrounding code from the module."
            ),
        },
        "imports_to_add": {
            "type": "array",
            "items": {"type": "string"},
            "description": (
                "Complete ES-module import statements that map_item needs. "
                "Normally empty: Zeeschuimer's `js/lib.js` (which provides MappedItem, "
                "MissingMappedField, normalize_url_encoding, strip_tags) is loaded as a "
                "plain script, NOT an ES module — its declarations are already global, "
                "so do not write `import { X } from '../js/lib.js'`. Only populate this "
                "if you genuinely need to import from another ES module."
            ),
        },
        "helpers_to_add": {
            "type": "array",
            "items": {"type": "string"},
            "description": (
                "Full source of any helper functions map_item depends on (e.g. a JS "
                "port of normalize_url_encoding). Empty array if none needed."
            ),
        },
        "commentary": {
            "type": "string",
            "description": (
                "Notes for the human reviewer: assumptions made, fields you were "
                "unsure about, Python idioms that don't translate cleanly. Plain text."
            ),
        },
    },
}

SYSTEM_PROMPT = (
    "You translate 4CAT Python `map_item` functions into JavaScript for the "
    "Zeeschuimer browser extension. You return ONLY the new map_item function, "
    "any imports it needs, any helper functions it depends on, and commentary "
    "for the human reviewer. You NEVER return the surrounding module file. "
    "You preserve the field names produced by the Python function exactly. "
    "You do not invent fields not present in the Python output. "
    "You output raw JavaScript source — never wrap it in markdown code fences "
    "(```js, ```javascript, etc.). The fields in your structured response are "
    "already typed as code; fences make them invalid."
)


# Whitelist of helpers that Zeeschuimer makes available as globals at runtime.
# `js/lib.js` is loaded as a plain <script>, not as an ES module, so its top-
# level declarations are global — they must NOT be imported. Anything not on
# this list must be inlined or added to `helpers_to_add`. Update this list
# whenever new helpers are added to `js/lib.js`.
AVAILABLE_JS_HELPERS = [
    {
        "name": "MappedItem",
        "kind": "class",
        "usage": "new MappedItem({field: value, ...})",
        "note": "Wraps the return value of map_item. Always instantiate with `new`.",
    },
    {
        "name": "MissingMappedField",
        "kind": "class",
        "usage": "new MissingMappedField(value, label)",
        "note": "Represents a field that may legitimately be missing. Always instantiate with `new`.",
    },
    {
        "name": "normalize_url_encoding",
        "kind": "function",
        "usage": "normalize_url_encoding(url)",
        "note": "Direct port of the Python helper of the same name.",
    },
    {
        "name": "strip_tags",
        "kind": "function",
        "usage": "strip_tags(html, convertNewlines = true)",
        "note": "Direct port of the Python helper of the same name.",
    },
    {
        "name": "formatUtcTimestamp",
        "kind": "function",
        "usage": "formatUtcTimestamp(timestamp)",
        "note": "Formats a UTC timestamp as a readable string.",
    }
]


def _format_available_helpers() -> str:
    lines = []
    for h in AVAILABLE_JS_HELPERS:
        lines.append(
            f"- `{h['name']}` ({h['kind']}, global) — {h['note']} "
            f"Usage: `{h['usage']}`."
        )
    return "\n".join(lines)


def is_zeeschuimer_datasource(python_path: Path) -> bool:
    """
    Returns True if the given Python file defines a 4CAT Search subclass with
    `is_from_zeeschuimer = True` as a class attribute.
    """
    try:
        tree = ast.parse(python_path.read_text(encoding="utf-8"))
    except (SyntaxError, OSError):
        return False

    for node in ast.walk(tree):
        if not isinstance(node, ast.ClassDef):
            continue
        for stmt in node.body:
            if not isinstance(stmt, ast.Assign):
                continue
            for target in stmt.targets:
                if isinstance(target, ast.Name) and target.id == "is_from_zeeschuimer":
                    if isinstance(stmt.value, ast.Constant) and stmt.value.value is True:
                        return True
    return False


def _find_zeeschuimer_class(tree: ast.Module) -> Optional[ast.ClassDef]:
    """Return the first class in the tree with `is_from_zeeschuimer = True`."""
    for node in ast.walk(tree):
        if not isinstance(node, ast.ClassDef):
            continue
        for stmt in node.body:
            if not isinstance(stmt, ast.Assign):
                continue
            for target in stmt.targets:
                if isinstance(target, ast.Name) and target.id == "is_from_zeeschuimer":
                    if isinstance(stmt.value, ast.Constant) and stmt.value.value is True:
                        return node
    return None


def _collect_map_item_call_graph(cls: ast.ClassDef) -> dict:
    """
    Starting from `map_item` on `cls`, walk same-class methods called
    transitively (via `self.X` or `<ClassName>.X`) and return a dict
    {method_name: ast.FunctionDef}. Returns empty dict if `map_item` not found.
    """
    methods = {
        m.name: m for m in cls.body if isinstance(m, (ast.FunctionDef, ast.AsyncFunctionDef))
    }
    if "map_item" not in methods:
        return {}

    needed = {"map_item": methods["map_item"]}
    frontier = ["map_item"]
    while frontier:
        name = frontier.pop()
        for n in ast.walk(needed[name]):
            if not isinstance(n, ast.Call):
                continue
            func = n.func
            if not isinstance(func, ast.Attribute):
                continue
            attr_name = func.attr
            if attr_name not in methods or attr_name in needed:
                continue
            value = func.value
            # Match `self.X(...)` and `<ClassName>.X(...)` — the two forms 4CAT
            # datasources use to call same-class methods (since map_item is
            # @staticmethod and references siblings via the class name).
            if isinstance(value, ast.Name) and value.id in ("self", cls.name):
                needed[attr_name] = methods[attr_name]
                frontier.append(attr_name)
    return needed


def extract_map_item_ast_dump(source: str) -> Optional[str]:
    """
    Return a normalized ast.dump of the Zeeschuimer datasource's `map_item`
    function plus any same-class helpers it transitively calls. Returns None
    if the file isn't a Zeeschuimer datasource or has no `map_item`. Used for
    skip-unchanged comparison: identical dumps mean no semantic change in the
    code we care about translating.
    """
    try:
        tree = ast.parse(source)
    except (SyntaxError, ValueError):
        return None
    cls = _find_zeeschuimer_class(tree)
    if cls is None:
        return None
    call_graph = _collect_map_item_call_graph(cls)
    if not call_graph:
        return None
    # Sort for stability; concatenate dumps separated by a marker.
    parts = [ast.dump(call_graph[name]) for name in sorted(call_graph)]
    return "\n---\n".join(parts)


def detect_used_python_helpers(source: str) -> list:
    """
    Return a sorted list of names imported from `common.lib.*` or
    `backend.lib.*` that are referenced inside map_item's call graph and are
    NOT already known to be available as JS globals. These are candidates for
    porting to Zeeschuimer (or for inlining manually) and should be flagged
    to 4CAT devs.

    Returns names like ["convert_to_int", "timify"] — bare helper names, not
    qualified module paths.
    """
    try:
        tree = ast.parse(source)
    except (SyntaxError, ValueError):
        return []
    cls = _find_zeeschuimer_class(tree)
    if cls is None:
        return []
    call_graph = _collect_map_item_call_graph(cls)
    if not call_graph:
        return []

    # Names imported from 4CAT internals (not stdlib, not 3rd-party).
    tracked_imports = {}
    for node in ast.walk(tree):
        if not isinstance(node, ast.ImportFrom):
            continue
        mod = node.module or ""
        if mod.startswith("common.lib") or mod.startswith("backend.lib"):
            for alias in node.names:
                local_name = alias.asname or alias.name
                tracked_imports[local_name] = mod

    if not tracked_imports:
        return []

    known_global_names = {h["name"] for h in AVAILABLE_JS_HELPERS}

    # Collect every Name reference inside any function in the call graph.
    referenced = set()
    for fn in call_graph.values():
        for n in ast.walk(fn):
            if isinstance(n, ast.Name):
                referenced.add(n.id)

    used_unknown = sorted(
        name
        for name in referenced
        if name in tracked_imports and name not in known_global_names
    )
    return used_unknown


def git_show(repo_root: Path, ref: str, rel_path: str) -> Optional[str]:
    """
    Read the contents of `rel_path` at the given git `ref` from `repo_root`.
    Returns the file contents, or None if the file didn't exist at that ref
    or git failed for any other reason. Never raises.
    """
    try:
        result = subprocess.run(
            ["git", "show", f"{ref}:{rel_path}"],
            cwd=str(repo_root),
            capture_output=True,
            text=True,
            timeout=10,
        )
    except (FileNotFoundError, subprocess.TimeoutExpired):
        return None
    if result.returncode != 0:
        return None
    return result.stdout


def discover_bootstrap_files(repo_root: Path) -> list[Path]:
    """
    Find every datasource file in PLATFORM_MAP whose class is a Zeeschuimer
    datasource. Returns absolute paths.
    """
    found = []
    for rel in PLATFORM_MAP:
        path = repo_root / rel
        if path.exists() and is_zeeschuimer_datasource(path):
            found.append(path)
    return sorted(found)


def build_user_prompt(python_source: str, existing_module_source: str, python_rel: str) -> str:
    helpers_block = _format_available_helpers()
    return (
        f"# Source Python file (datasources/{python_rel})\n"
        "This is the file that just changed in 4CAT. The `map_item` function on the "
        "class is the source of truth — your JavaScript translation must produce an "
        "object with the same field names and equivalent values.\n\n"
        f"```python\n{python_source}\n```\n\n"
        "# Existing Zeeschuimer module\n"
        "This module's `capture()` function returns the raw items that will be "
        "passed to `map_item(item)` as `item`. Use it to understand the input shape "
        "and to match the existing code style (ES modules, `export` keyword, etc.).\n\n"
        f"```javascript\n{existing_module_source}\n```\n\n"
        "# Available Zeeschuimer JS helpers (globals)\n"
        "Zeeschuimer loads `js/lib.js` as a plain `<script>`, NOT as an ES "
        "module. Its top-level declarations are global — available everywhere "
        "without any `import`. Use them by name only. The following are the "
        "helpers you may use; everything else must be implemented as JavaScript "
        "(inline in `map_item_function` or as separate snippets in `helpers_to_add`).\n\n"
        f"{helpers_block}\n\n"
        "# Imports — almost always none\n"
        "Do NOT write `import { MappedItem } from '../js/lib.js'` or any similar "
        "statement for the helpers above — `lib.js` is a script, not a module, "
        "and the import will fail at runtime. The `imports_to_add` field should "
        "normally be EMPTY; only include an import if you genuinely need to pull "
        "from another ES module (rare for `map_item`).\n\n"
        "Also forbidden, because they don't exist in JavaScript:\n"
        "- Anything from `common.lib.helpers` not listed above (e.g. `convert_to_int`, `timify`)\n"
        "- Anything from `common.lib.exceptions`, `common.lib.user_input`, `backend.lib.*`\n"
        "- Python stdlib modules (`datetime`, `urllib.parse`, `re`, `json`, `hashlib`, etc.) — use the JavaScript native equivalents instead.\n\n"
        "# Python → JavaScript translation rules\n"
        "- **Class instantiation**: JavaScript requires the `new` keyword. Python `MappedItem({...})` becomes JavaScript `new MappedItem({...})`. Same for `MissingMappedField`.\n"
        "- **datetime**: Python `datetime.utcfromtimestamp(t)` → JS `new Date(t * 1000)`; `datetime.now()` → `new Date()`; `.strftime('%Y-%m-%d %H:%M:%S')` → manual formatting via `toISOString()` / `Date` getters.\n"
        "- **URLs**: Python `urlparse(u)` / `parse_qs(q)` → JS `new URL(u)` / `url.searchParams`. The `URL` class auto-handles encoding.\n"
        "- **regex**: Python `re.compile(p).search(s)` → JS `s.match(p)` or `new RegExp(p).exec(s)`. Watch out for differing flag syntax.\n"
        "- **f-strings**: Python `f\"x {y}\"` → JS template literals `` `x ${y}` ``.\n"
        "- **dict iteration**: Python `d.get(k, default)` → JS `d[k] ?? default` or `(d[k] !== undefined ? d[k] : default)`.\n"
        "- **list comprehensions**: Python `[f(x) for x in xs if g(x)]` → JS `xs.filter(g).map(f)`.\n"
        "- **substring check**: Python `'x' in some_string` → JS `some_string.includes('x')`. NEVER write `'x' in some_string` in JS — JS's `in` operator on a string throws `TypeError`.\n"
        "- **regex**: STRONGLY prefer JS regex literals (`/pattern/flags`) over `new RegExp(\"pattern\")`. Regex literals are parsed by the JS engine directly, so `\\s`, `\\d`, `\\w`, `\\b` survive without string-escape mangling. The `RegExp` string constructor needs every backslash doubled and is a frequent source of bugs — avoid it unless the pattern is truly dynamic.\n\n"
        "# Common mistakes from past runs (the script lints for these and rejects matches)\n"
        "- Python `dict.get(k)` / `dict.get(k, default)` does NOT exist in JavaScript. Replace EVERY `.get(...)` with `[k]` or `[k] ?? default`. Pinterest- and Instagram-style code has many of these — translate every one.\n"
        "- Literal newlines inside string literals are a JS syntax error. Python `\"\\n\".join(xs)` becomes JS `xs.join(\"\\n\")` — keep the `\\n` as an escape sequence; do NOT put an actual newline character inside the quotes.\n"
        "- Python `'x' in some_string` (substring check) → JS `some_string.includes('x')`. JS's `in` operator on a string throws TypeError.\n"
        "- For regex, use JS regex literals (`/\\s+/g`) — never `new RegExp(\"\\\\s+\", \"g\")`. The string-constructor form is a backslash-escape minefield.\n"
        "- `MappedItem` and `MissingMappedField` are CLASSES — always use `new MappedItem({...})` and `new MissingMappedField(...)`, never bare calls.\n"
        "- `js/lib.js` is loaded as a script, NOT a module. Do NOT write `import { X } from '../js/lib.js'`. The helpers there are globals.\n"
        "- Python keywords don't exist in JS: `None` → `null`, `True`/`False` → `true`/`false`, `def` → `function`.\n"
        "- f-strings (`f\"x {y}\"`) don't exist in JS. Use template literals (`` `x ${y}` ``).\n\n"
        "# Before submitting, verify your output\n"
        "1. The function contains zero `.get(` calls.\n"
        "2. Every `MappedItem(` and `MissingMappedField(` is preceded by `new `.\n"
        "3. No string literal contains a raw newline character — use `\\n` escapes.\n"
        "4. No `'x' in someString` — use `someString.includes('x')`.\n"
        "5. Regexes use literal `/.../flags` syntax, not `new RegExp(\"...\")`.\n"
        "6. `imports_to_add` is empty unless you really need an ES-module import (it should NOT contain anything for `MappedItem` etc.).\n"
        "7. No Python keywords (`None`, `True`, `False`, `def`, f-strings).\n\n"
        "# Output format\n"
        "Use `export function map_item(item) { ... }` to match this module's ES-module style. "
        "Return raw JavaScript source — do NOT wrap fields in markdown code fences. "
        "The `imports_to_add` field is normally an empty array (the helpers above are global, not imported). "
        "The `helpers_to_add` field should contain full helper-function source (each entry one complete function)."
    )


# Remove these code fences that keep appearing in the LLM output, even when explicitly told not to use them.
_FENCE_OPEN = re.compile(r"^```(?:js|javascript|typescript|ts)?\s*\n?", re.IGNORECASE)
_FENCE_CLOSE = re.compile(r"\n?```\s*$")


def strip_code_fences(s: str) -> str:
    """
    Strip leading/trailing markdown code fences (```js, ```javascript, ``` etc.)
    Idempotent; returns the input unchanged if no fences found. Defensive
    post-processing because LLMs frequently wrap their answers in fences even
    when explicitly told not to.
    """
    if not s:
        return s
    s = s.strip()
    s = _FENCE_OPEN.sub("", s)
    s = _FENCE_CLOSE.sub("", s)
    return s.strip()

# If all else fails...
def parse_freetext_response(text: str) -> dict:
    """
    Fallback parser for when structured output is disabled or unreliable.
    Looks for a fenced JS block (the function) and treats remaining text as
    commentary.
    """
    js_match = re.search(r"```(?:js|javascript)\s*\n(.*?)```", text, re.DOTALL)
    map_item_function = js_match.group(1).strip() if js_match else ""
    commentary = re.sub(r"```(?:js|javascript)\s*\n.*?```", "", text, flags=re.DOTALL).strip()
    return {
        "map_item_function": map_item_function,
        "imports_to_add": [],
        "helpers_to_add": [],
        "commentary": commentary,
    }

# Helper to check for common issues
def _strip_js_comments(s: str) -> str:
    """Remove // and /* */ comments so they don't trip pattern checks."""
    s = re.sub(r"//[^\n]*", "", s)
    s = re.sub(r"/\*.*?\*/", "", s, flags=re.DOTALL)
    return s


# Regex checks for known anti-patterns the LLM produces.
# Each entry is (pattern, message). Stay conservative: false negatives are
# fine, false positives block valid code so they're worse.
LINT_PATTERNS = [
    (
        re.compile(r"\.get\("),
        "Python `dict.get()` does not exist in JavaScript. Replace every `.get(k)` with `[k]` and every `.get(k, default)` with `[k] ?? default`.",
    ),
    (
        re.compile(r"^\s*from\s+\S+\s+import\b", re.MULTILINE),
        "Python-style `from X import Y` statement found. JavaScript uses `import { Y } from 'X'` syntax (and only when really needed — Zeeschuimer helpers are globals).",
    ),
    (
        re.compile(r"import\s*(?:\{[^}]*\}|\*\s+as\s+\w+|\w+)\s+from\s+['\"]\.\.?/js/lib\.js['\"]"),
        "Do not import from `js/lib.js` — it is loaded as a script, its declarations are global.",
    ),
    (
        re.compile(r"\bNone\b"),
        "Python `None` is not valid JavaScript. Use `null`.",
    ),
    (
        re.compile(r"\bTrue\b"),
        "Python `True` is not valid JavaScript. Use `true` (lowercase).",
    ),
    (
        re.compile(r"\bFalse\b"),
        "Python `False` is not valid JavaScript. Use `false` (lowercase).",
    ),
    (
        re.compile(r"\bdef\s+\w+\s*\("),
        "Python `def` keyword found. Use JavaScript `function name(...)` declaration syntax.",
    ),
    (
        re.compile(r"\bf\"|\bf'"),
        "Python f-string detected (`f\"...\"` or `f'...'`). Use JavaScript template literals (`` `...${x}...` ``).",
    ),
    (
        # Python idiom: `'foo' in string_expr` for substring check. In JS this
        # throws TypeError. Right-hand side is an identifier with a method call
        # or property access, which strongly suggests "is this in that string".
        # `'key' in obj` (object membership) is valid JS but has no `.method()`
        # / no chained access on the rhs — this pattern targets the bug case.
        re.compile(r"['\"][^'\"\n]+['\"]\s+in\s+[A-Za-z_$][\w$]*(?:\.[A-Za-z_$][\w$]*)+"),
        "Python-style `'x' in expr.method()` substring check found. JavaScript's `in` operator on a string throws TypeError; use `expr.method().includes('x')` instead.",
    ),
    (
        re.compile(r"\bnew\s+RegExp\s*\("),
        "`new RegExp(\"...\")` is fragile — every backslash needs doubling and JSON-escape pipelines mangle it. Prefer regex literal syntax: `/pattern/flags`.",
    ),
]


# Lexer that matches JS string and template literals as whole units. Used to
# check whether a single- or double-quoted literal contains a raw newline (a
# JS syntax error). Template literals are allowed to span lines so they're
# matched and skipped. Regex matches escapes (\\.) so embedded `\"` etc. don't
# prematurely close the string.
_JS_STRING_LITERAL = re.compile(
    r'''
        (?P<dq>"(?:[^"\\]|\\.)*")
      | (?P<sq>'(?:[^'\\]|\\.)*')
      | (?P<tl>`(?:[^`\\]|\\.)*`)
    ''',
    re.DOTALL | re.VERBOSE,
)


def _has_literal_newline_in_string(source: str) -> bool:
    for m in _JS_STRING_LITERAL.finditer(source):
        if m.group("tl"):
            continue  # template literals legally span lines
        if "\n" in m.group(0):
            return True
    return False


def lint_translation(translation: dict) -> list:
    """
    Scan the generated JS for known bugs. Returns a list of error strings
    (empty if clean). Runs on `map_item_function` and each `helpers_to_add`
    entry. Comments are stripped before scanning to avoid false positives
    on commentary text.
    """
    issues = []
    sources = []
    fn = translation.get("map_item_function") or ""
    if fn:
        sources.append(("map_item_function", fn))
    for i, h in enumerate(translation.get("helpers_to_add") or []):
        if isinstance(h, str) and h:
            sources.append((f"helpers_to_add[{i}]", h))

    for label, source in sources:
        clean = _strip_js_comments(source)

        seen = set()
        for regex, message in LINT_PATTERNS:
            if regex.search(clean) and message not in seen:
                issues.append(f"[{label}] {message}")
                seen.add(message)

        # Class instantiation without `new` (variable-width lookbehind, so
        # check the chars before each match manually).
        for cls in ("MappedItem", "MissingMappedField"):
            pattern = re.compile(rf"\b{cls}\s*\(")
            reported = False
            for m in pattern.finditer(clean):
                before = clean[max(0, m.start() - 8) : m.start()]
                if not re.search(r"\bnew\s+$", before):
                    if not reported:
                        issues.append(
                            f"[{label}] `{cls}` instantiated without `new` keyword "
                            f"(at offset {m.start()}). All class instantiations need `new`."
                        )
                        reported = True

        # Literal newlines inside single- or double-quoted strings (a JS
        # syntax error). The LLM sometimes emits e.g. `.join('\n')` as
        # `.join('<actual newline>')` which doesn't parse.
        if _has_literal_newline_in_string(clean):
            issues.append(
                f"[{label}] Literal newline inside a string literal — JS strings "
                f"can't span lines without escape (`\"\\n\"`) or template literals "
                f"(`` `\\n` ``)."
            )

    return issues


def validate_translation(translation: dict) -> Optional[str]:
    """
    Returns None if the translation passes basic sanity checks, else a string
    describing what went wrong.
    """
    fn = translation.get("map_item_function", "").strip()
    if not fn:
        return "LLM returned empty map_item_function"
    if not re.search(r"\bmap_item\b", fn):
        return "LLM output does not contain `map_item` identifier"
    if not re.search(r"function\s+map_item|map_item\s*=|map_item\s*:", fn):
        return "LLM output does not declare `map_item` as a function"
    return None


def splice_into_module(existing: str, translation: dict, python_rel: str) -> str:
    """
    Insert / replace the auto-generated marker blocks in the JS
    module text.

    Raises ValueError if exactly one of (start, end) markers is present —
    that means the file is corrupted or partially hand-edited and we should
    refuse to touch it.
    """
    main_block_body = []
    for helper in translation.get("helpers_to_add", []):
        helper = helper.strip()
        if helper:
            main_block_body.append(helper)
    fn = translation["map_item_function"].strip()
    main_block_body.append(fn)
    main_block = (
        f"{BLOCK_MARKER_START}\n"
        f"// (regenerated from {python_rel})\n"
        + "\n\n".join(main_block_body)
        + f"\n{BLOCK_MARKER_END}\n"
    )

    imports = [imp.strip() for imp in translation.get("imports_to_add", []) if imp.strip()]
    # Drop imports that already appear verbatim outside the marker block.
    existing_outside_block = re.sub(
        re.escape(BLOCK_MARKER_START) + r".*?" + re.escape(BLOCK_MARKER_END) + r"\n?",
        "",
        existing,
        flags=re.DOTALL,
    )
    existing_outside_imports_block = re.sub(
        re.escape(IMPORTS_MARKER_START) + r".*?" + re.escape(IMPORTS_MARKER_END) + r"\n?",
        "",
        existing_outside_block,
        flags=re.DOTALL,
    )
    imports = [imp for imp in imports if imp not in existing_outside_imports_block]

    imports_block = ""
    if imports:
        imports_block = (
            f"{IMPORTS_MARKER_START}\n"
            + "\n".join(imports)
            + f"\n{IMPORTS_MARKER_END}\n"
        )

    updated = existing

    # Replace or insert imports block.
    has_imports_start = IMPORTS_MARKER_START in updated
    has_imports_end = IMPORTS_MARKER_END in updated
    if has_imports_start ^ has_imports_end:
        raise ValueError(
            "Auto-generated imports markers are partially missing in the existing "
            "module — refusing to overwrite. Restore both markers or remove both."
        )
    if has_imports_start and has_imports_end:
        updated = re.sub(
            re.escape(IMPORTS_MARKER_START) + r".*?" + re.escape(IMPORTS_MARKER_END) + r"\n?",
            imports_block,
            updated,
            count=1,
            flags=re.DOTALL,
        )
    elif imports_block:
        # Prepend at top of file.
        if updated and not updated.startswith("\n"):
            updated = imports_block + "\n" + updated
        else:
            updated = imports_block + updated

    # Replace or append main block.
    has_main_start = BLOCK_MARKER_START in updated
    has_main_end = BLOCK_MARKER_END in updated
    if has_main_start ^ has_main_end:
        raise ValueError(
            "Auto-generated map_item markers are partially missing in the existing "
            "module — refusing to overwrite. Restore both markers or remove both."
        )
    if has_main_start and has_main_end:
        updated = re.sub(
            re.escape(BLOCK_MARKER_START) + r".*?" + re.escape(BLOCK_MARKER_END) + r"\n?",
            main_block,
            updated,
            count=1,
            flags=re.DOTALL,
        )
    else:
        if not updated.endswith("\n"):
            updated += "\n"
        updated += "\n" + main_block

    return updated


REASONING_KEYS = ("reasoning_content", "reasoning", "thinking", "thought")


def _extract_reasoning(chunk) -> str:
    """
    Pull reasoning/thinking tokens off a LangChain chunk. Different model
    families surface them under different keys, so try several.
    """
    kwargs = getattr(chunk, "additional_kwargs", None) or {}
    for key in REASONING_KEYS:
        val = kwargs.get(key)
        if isinstance(val, str) and val:
            return val
    return ""


def call_llm_streaming(llm: LLMAdapter, user_prompt: str, system_prompt: str) -> str:
    """
    Stream the LLM response to stderr chunk-by-chunk and return the accumulated
    *visible content* (reasoning tokens are surfaced live but NOT included in
    the returned string — they aren't part of the parseable answer).

    For reasoning models like gpt-oss / deepseek-r1, the model spends a long
    time emitting reasoning tokens before producing the visible answer; without
    surfacing them the stream looks frozen. We mark the reasoning vs content
    transitions so the user can tell what phase the model is in.
    """
    from langchain_core.messages import HumanMessage, SystemMessage

    messages = []
    if system_prompt:
        messages.append(SystemMessage(content=system_prompt))
    messages.append(HumanMessage(content=user_prompt))

    sys.stderr.write("\n--- LLM stream begin ---\n")
    sys.stderr.flush()

    content_chunks: list[str] = []
    state: Optional[str] = None  # "reasoning" | "content"

    for chunk in llm.llm.stream(messages):
        reasoning = _extract_reasoning(chunk)
        content = getattr(chunk, "content", "") or ""

        if reasoning:
            if state != "reasoning":
                sys.stderr.write("\n--- reasoning ---\n")
                state = "reasoning"
            sys.stderr.write(reasoning)
            sys.stderr.flush()

        if content:
            if state != "content":
                # transitioning from reasoning (or nothing) to visible output
                sys.stderr.write("\n--- output ---\n")
                state = "content"
            sys.stderr.write(content)
            sys.stderr.flush()
            content_chunks.append(content)

    sys.stderr.write("\n--- LLM stream end ---\n")
    sys.stderr.flush()
    return "".join(content_chunks)


def extract_raw_from_exception(exc: BaseException) -> Optional[str]:
    """
    Pull whatever raw LLM output we can find off a LangChain exception. Tries
    several attribute names since they vary by LangChain version. Returns None
    if nothing recoverable.
    """
    for attr in ("llm_output", "observation", "output"):
        val = getattr(exc, attr, None)
        if isinstance(val, str):
            return val
    return None


def translate_one(
    llm: LLMAdapter,
    python_path: Path,
    repo_root: Path,
    zeeschuimer_root: Path,
    use_structured_output: bool,
    stream: bool,
    strict_lint: bool,
    skip_unchanged_against: Optional[str] = None,
) -> dict:
    """
    Translate one Python file. Returns a manifest entry dict.
    """
    rel = python_path.relative_to(repo_root).as_posix()
    entry = {
        "python_file": rel,
        "js_file": None,
        "status": "failed",
        "commentary": "",
        "duration_seconds": None,
        "raw_response": None,
        "lint_warnings": [],
        "unknown_helpers": [],
        "translation": None,
        "error": None,
    }

    if not is_zeeschuimer_datasource(python_path):
        entry["status"] = "skipped"
        entry["error"] = "not a Zeeschuimer datasource (is_from_zeeschuimer != True)"
        return entry

    js_rel = PLATFORM_MAP.get(rel)
    if not js_rel:
        entry["status"] = "skipped"
        entry["error"] = f"no Zeeschuimer module mapped for {rel}"
        return entry
    entry["js_file"] = js_rel

    js_path = zeeschuimer_root / js_rel
    if not js_path.exists():
        entry["status"] = "skipped"
        entry["error"] = f"Zeeschuimer module {js_rel} does not exist in checkout"
        return entry

    python_source = python_path.read_text(encoding="utf-8")

    # Skip-unchanged: if the map_item call graph hasn't changed at AST level
    # vs. the requested ref, don't bother calling the LLM. Saves ~40s per
    # untouched datasource on push triggers where some other file in the
    # commit incidentally matches the path filter.
    if skip_unchanged_against:
        prev_source = git_show(repo_root, skip_unchanged_against, rel)
        if prev_source is not None:
            current_dump = extract_map_item_ast_dump(python_source)
            previous_dump = extract_map_item_ast_dump(prev_source)
            if (
                current_dump is not None
                and previous_dump is not None
                and current_dump == previous_dump
            ):
                entry["status"] = "skipped"
                entry["error"] = (
                    f"map_item call graph unchanged vs {skip_unchanged_against}; "
                    f"no LLM call needed"
                )
                return entry

    # Detect any 4CAT-internal Python helpers the map_item call graph
    # references that aren't already in AVAILABLE_JS_HELPERS. These are
    # candidates for porting to Zeeschuimer's lib.js — flag them to 4CAT
    # devs via the manifest and PR body.
    entry["unknown_helpers"] = detect_used_python_helpers(python_source)

    existing_module = js_path.read_text(encoding="utf-8")
    user_prompt = build_user_prompt(python_source, existing_module, rel)

    started = time.monotonic()
    raw_response: Optional[str] = None
    translation: Optional[dict] = None
    llm_error: Optional[str] = None

    try:
        if stream:
            raw_response = call_llm_streaming(llm, user_prompt, SYSTEM_PROMPT)
            translation = parse_freetext_response(raw_response)
        elif use_structured_output:
            try:
                response = llm.generate_text(user_prompt, system_prompt=SYSTEM_PROMPT)
            except Exception as e:
                raw_response = extract_raw_from_exception(e)
                llm_error = f"LLM call failed: {e}"
                response = None
            if response is not None:
                if isinstance(response, dict):
                    translation = response
                    # Structured-output success doesn't expose the raw text.
                else:
                    llm_error = (
                        f"Expected dict from structured output, got "
                        f"{type(response).__name__}"
                    )
        else:
            response = llm.generate_text(user_prompt, system_prompt=SYSTEM_PROMPT)
            raw_response = getattr(response, "content", str(response))
            translation = parse_freetext_response(raw_response)
    except Exception as e:
        raw_response = raw_response or extract_raw_from_exception(e)
        llm_error = f"LLM call failed: {e}"

    entry["duration_seconds"] = round(time.monotonic() - started, 2)
    entry["raw_response"] = raw_response

    if llm_error:
        entry["error"] = llm_error
        return entry
    if translation is None:
        entry["error"] = "no translation produced (no error raised, no dict returned)"
        return entry

    # Defensive: strip stray markdown code fences from the function source and
    # each helper. Models wrap things in ```js even when instructed not to.
    if isinstance(translation.get("map_item_function"), str):
        translation["map_item_function"] = strip_code_fences(translation["map_item_function"])
    helpers = translation.get("helpers_to_add")
    if isinstance(helpers, list):
        translation["helpers_to_add"] = [
            strip_code_fences(h) if isinstance(h, str) else h for h in helpers
        ]

    bad = validate_translation(translation)
    if bad:
        entry["translation"] = translation
        entry["error"] = bad
        return entry

    lint_issues = lint_translation(translation)
    if lint_issues:
        if strict_lint:
            entry["translation"] = translation
            entry["lint_warnings"] = lint_issues
            entry["error"] = "Lint issues (--strict-lint):\n  - " + "\n  - ".join(lint_issues)
            return entry
        # Non-strict (default): record as warnings and let the file ship. The
        # reviewer sees the issues in the PR body and fixes them by hand.
        entry["lint_warnings"] = lint_issues

    try:
        spliced = splice_into_module(existing_module, translation, rel)
    except ValueError as e:
        entry["translation"] = translation
        entry["error"] = str(e)
        return entry

    # Per-file dedup: only write if the spliced output actually differs from
    # what's on disk. Stops nondeterministic LLM whitespace from polluting
    # the PR diff for files where the translation is effectively unchanged.
    if spliced != existing_module:
        js_path.write_text(spliced, encoding="utf-8")
        entry["js_changed"] = True
    else:
        entry["js_changed"] = False
    entry["status"] = "ok"
    entry["commentary"] = translation.get("commentary", "").strip()
    # Keep parsed translation on warning entries so the PR / reviewer can see
    # exactly what was emitted alongside the warnings.
    if entry["lint_warnings"]:
        entry["translation"] = translation
    return entry


def main():
    cli = argparse.ArgumentParser(description=__doc__)
    group = cli.add_mutually_exclusive_group(required=True)
    group.add_argument("--files", nargs="+", help="Specific datasource files to translate.")
    group.add_argument(
        "--bootstrap",
        action="store_true",
        help="Translate every Zeeschuimer datasource in the repo.",
    )
    cli.add_argument(
        "--zeeschuimer-checkout",
        required=True,
        type=Path,
        help="Path to a local clone of the Zeeschuimer repo.",
    )
    cli.add_argument(
        "--output-manifest",
        required=True,
        type=Path,
        help="Where to write the JSON manifest of results.",
    )
    cli.add_argument(
        "--model",
        default=os.environ.get("LLM_MODEL", DEFAULT_MODEL),
        help=f"Ollama model to use (default: {DEFAULT_MODEL}, or $LLM_MODEL).",
    )
    cli.add_argument(
        "--no-structured-output",
        action="store_true",
        help="Disable JSON-schema structured output; parse the response as free text.",
    )
    cli.add_argument(
        "--stream",
        action="store_true",
        help=(
            "Stream LLM output to stderr as it is generated, so you can watch a "
            "slow model work. Implies --no-structured-output (streaming and "
            "structured output don't mix cleanly)."
        ),
    )
    cli.add_argument(
        "--no-fail-fast",
        action="store_true",
        help=(
            "Continue translating remaining files even after one fails. By "
            "default the script aborts on the first failure, since failures here "
            "are typically configuration- or model-correlated and continuing "
            "wastes LLM time."
        ),
    )
    cli.add_argument(
        "--strict-lint",
        action="store_true",
        help=(
            "Treat lint findings (Python `.get()`, missing `new`, literal newlines "
            "in strings, etc.) as failures rather than warnings. Default is "
            "warnings — the file still ships and the PR body surfaces the "
            "issues so the reviewer can fix them by hand."
        ),
    )
    cli.add_argument(
        "--skip-unchanged-against",
        metavar="REF",
        default=None,
        help=(
            "For each input file, compare the map_item call graph (map_item + "
            "any same-class helpers it transitively calls) against the file's "
            "version at the given git ref. If the AST-level dump is identical, "
            "skip translation entirely. Used by the GitHub Action on push "
            "triggers (REF = github.event.before) to avoid spending LLM time "
            "on files where map_item didn't actually change."
        ),
    )
    args = cli.parse_args()

    dmi_ollama_key = os.environ.get("DMI_OLLAMA_KEY")
    if not dmi_ollama_key:
        sys.exit("Error: DMI_OLLAMA_KEY environment variable not set.")

    repo_root = Path(__file__).resolve().parent.parent

    if args.bootstrap:
        files = discover_bootstrap_files(repo_root)
        if not files:
            sys.exit("No Zeeschuimer datasources found to bootstrap.")
    else:
        files = [Path(f).resolve() for f in args.files]

    llm = LLMAdapter(
        provider="ollama",
        model=args.model,
        base_url="https://ollama.digitalmethods.net",
        temperature=0.2,
        max_tokens=8192,
        client_kwargs={"headers": {"X-API-KEY": dmi_ollama_key}},
    )

    use_structured_output = not args.no_structured_output and not args.stream
    if use_structured_output:
        try:
            llm.set_structure(LLM_SCHEMA)
        except Exception as e:
            print(
                f"Warning: could not enable structured output ({e}); "
                "falling back to free-text parsing.",
                file=sys.stderr,
            )
            use_structured_output = False

    fail_fast = not args.no_fail_fast
    print(
        f"Using model: {args.model} "
        f"(provider: ollama, structured_output: {use_structured_output}, "
        f"stream: {args.stream}, fail_fast: {fail_fast}, "
        f"strict_lint: {args.strict_lint}, "
        f"skip_unchanged_against: {args.skip_unchanged_against or 'off'})"
    )

    entries = []
    overall_started = time.monotonic()
    for python_path in files:
        rel_for_log = python_path.relative_to(repo_root).as_posix()
        print(f"Translating {rel_for_log}...", flush=True)
        per_file_started = time.monotonic()
        try:
            entry = translate_one(
                llm,
                python_path,
                repo_root,
                args.zeeschuimer_checkout.resolve(),
                use_structured_output,
                args.stream,
                args.strict_lint,
                skip_unchanged_against=args.skip_unchanged_against,
            )
        except Exception as e:
            entry = {
                "python_file": str(python_path),
                "js_file": None,
                "status": "failed",
                "commentary": "",
                "duration_seconds": round(time.monotonic() - per_file_started, 2),
                "error": f"unexpected exception: {e}\n{traceback.format_exc()}",
            }
        entry["model"] = args.model
        entries.append(entry)
        dur = entry.get("duration_seconds")
        dur_str = f" in {dur}s" if dur is not None else ""
        err_str = f" ({entry['error']})" if entry.get("error") else ""
        warn_str = (
            f" with {len(entry['lint_warnings'])} lint warning(s)"
            if entry.get("lint_warnings")
            else ""
        )
        unknowns = entry.get("unknown_helpers") or []
        unknown_str = (
            f" [unknown helpers: {', '.join(unknowns)}]" if unknowns else ""
        )
        print(f"  -> {entry['status']}{warn_str}{dur_str}{err_str}{unknown_str}", flush=True)

        if entry["status"] == "failed" and not args.no_fail_fast:
            remaining = len(files) - len(entries)
            if remaining > 0:
                print(
                    f"\nFail-fast: aborting after first failure; skipping "
                    f"{remaining} remaining file(s). Pass --no-fail-fast to continue past failures.",
                    flush=True,
                )
            break

    overall_duration = round(time.monotonic() - overall_started, 2)
    # Aggregate unknown helpers across all entries — the unique set of Python
    # helper names map_item references that aren't yet ported to Zeeschuimer.
    aggregate_unknown_helpers = sorted({
        h for e in entries for h in (e.get("unknown_helpers") or [])
    })
    manifest = {
        "model": args.model,
        "provider": "ollama",
        "structured_output": use_structured_output,
        "stream": args.stream,
        "fail_fast": fail_fast,
        "strict_lint": args.strict_lint,
        "skip_unchanged_against": args.skip_unchanged_against,
        "total_duration_seconds": overall_duration,
        "aggregate_unknown_helpers": aggregate_unknown_helpers,
        "entries": entries,
    }
    args.output_manifest.parent.mkdir(parents=True, exist_ok=True)
    args.output_manifest.write_text(json.dumps(manifest, indent=2), encoding="utf-8")

    n_ok = sum(1 for e in entries if e["status"] == "ok")
    n_with_warnings = sum(1 for e in entries if e["status"] == "ok" and e.get("lint_warnings"))
    n_failed = sum(1 for e in entries if e["status"] == "failed")
    n_skipped = sum(1 for e in entries if e["status"] == "skipped")
    print(
        f"\nDone with model `{args.model}` in {overall_duration}s: "
        f"{n_ok} ok ({n_with_warnings} with warnings), "
        f"{n_failed} failed, {n_skipped} skipped."
    )
    print(f"Manifest written to {args.output_manifest}")

    if n_ok == 0 and n_failed > 0:
        sys.exit(1)


if __name__ == "__main__":
    main()
