"""
Translate 4CAT Zeeschuimer-import datasource `map_item` functions from Python
to JavaScript and splice them into the corresponding Zeeschuimer
`modules/<platform>.js` file.

Designed to be invoked by a GitHub Action whenever a Zeeschuimer datasource's
Python file changes on master. Can also be run locally for testing or via
`workflow_dispatch` with `--bootstrap` to translate every datasource at once.

The LLM produces only the new `map_item` function (plus any imports/helpers it
needs and free-text commentary). This script does the file integration: it
locates a marker block in the existing JS module and replaces its contents,
preserving every hand-written line outside the markers.

Usage:
    DMI_OLLAMA_KEY=... python helper-scripts/map_item_converter.py \\
        --files datasources/tiktok/search_tiktok.py \\
        --zeeschuimer-checkout ../zeeschuimer \\
        --output-manifest /tmp/manifest.json
"""
import argparse
import ast
import json
import os
import re
import sys
import traceback
from pathlib import Path
from typing import Optional

sys.path.insert(0, os.path.join(os.path.abspath(os.path.dirname(__file__)), ".."))

from common.lib.llm import LLMAdapter


# 4CAT datasource path -> Zeeschuimer module path (relative to checkout root).
# Verified against https://github.com/digitalmethodsinitiative/zeeschuimer/tree/master/modules
# Note: facebook has no Zeeschuimer module today, so it's intentionally absent.
PLATFORM_MAP = {
    "datasources/douyin/search_douyin.py": "modules/douyin.js",
    "datasources/gab/search_gab.py": "modules/gab.js",
    "datasources/imgur/search_imgur.py": "modules/imgur.js",
    "datasources/instagram/search_instagram.py": "modules/instagram.js",
    "datasources/linkedin/search_linkedin.py": "modules/linkedin.js",
    "datasources/ninegag/search_9gag.py": "modules/9gag.js",
    "datasources/pinterest/search_pinterest.py": "modules/pinterest.js",
    "datasources/threads/search_threads.py": "modules/threads.js",
    "datasources/tiktok/search_tiktok.py": "modules/tiktok.js",
    "datasources/tiktok_comments/search_tiktok_comments.py": "modules/tiktok-comments.js",
    "datasources/truth/search_truth.py": "modules/truth.js",
    "datasources/twitter-import/search_twitter.py": "modules/twitter.js",
    "datasources/xiaohongshu/search_rednote.py": "modules/rednote.js",
    "datasources/xiaohongshu_comments/search_rednote_comments.py": "modules/rednote-comments.js",
}

DEFAULT_MODEL = "gemma3:4b"

IMPORTS_MARKER_START = "// === auto-generated imports for map_item — DO NOT EDIT BY HAND ==="
IMPORTS_MARKER_END = "// === end auto-generated imports ==="
BLOCK_MARKER_START = "// === auto-generated by 4cat map_item sync — DO NOT EDIT BY HAND ==="
BLOCK_MARKER_END = "// === end auto-generated ==="

LLM_SCHEMA = {
    "title": "MapItemTranslation",
    "type": "object",
    "required": ["map_item_function", "imports_to_add", "helpers_to_add", "commentary"],
    "properties": {
        "map_item_function": {
            "type": "string",
            "description": (
                "Full JavaScript source of the new map_item function. Must include "
                "the function declaration (e.g. 'export function map_item(item) {...}'). "
                "Do not include surrounding code from the module."
            ),
        },
        "imports_to_add": {
            "type": "array",
            "items": {"type": "string"},
            "description": (
                "Complete import statements (one per array entry) that map_item needs "
                "and that are not already present in the existing module. Empty array "
                "if none needed."
            ),
        },
        "helpers_to_add": {
            "type": "array",
            "items": {"type": "string"},
            "description": (
                "Full source of any helper functions map_item depends on (e.g. a JS "
                "port of normalize_url_encoding). Empty array if none needed."
            ),
        },
        "commentary": {
            "type": "string",
            "description": (
                "Notes for the human reviewer: assumptions made, fields you were "
                "unsure about, Python idioms that don't translate cleanly. Plain text."
            ),
        },
    },
}

SYSTEM_PROMPT = (
    "You translate 4CAT Python `map_item` functions into JavaScript for the "
    "Zeeschuimer browser extension. You return ONLY the new map_item function, "
    "any imports it needs, any helper functions it depends on, and commentary "
    "for the human reviewer. You NEVER return the surrounding module file. "
    "You preserve the field names produced by the Python function exactly. "
    "You do not invent fields not present in the Python output."
)


def is_zeeschuimer_datasource(python_path: Path) -> bool:
    """
    Returns True if the given Python file defines a 4CAT Search subclass with
    `is_from_zeeschuimer = True` as a class attribute.
    """
    try:
        tree = ast.parse(python_path.read_text(encoding="utf-8"))
    except (SyntaxError, OSError):
        return False

    for node in ast.walk(tree):
        if not isinstance(node, ast.ClassDef):
            continue
        for stmt in node.body:
            if not isinstance(stmt, ast.Assign):
                continue
            for target in stmt.targets:
                if isinstance(target, ast.Name) and target.id == "is_from_zeeschuimer":
                    if isinstance(stmt.value, ast.Constant) and stmt.value.value is True:
                        return True
    return False


def discover_bootstrap_files(repo_root: Path) -> list[Path]:
    """
    Find every datasource file in PLATFORM_MAP whose class is a Zeeschuimer
    datasource. Returns absolute paths.
    """
    found = []
    for rel in PLATFORM_MAP:
        path = repo_root / rel
        if path.exists() and is_zeeschuimer_datasource(path):
            found.append(path)
    return sorted(found)


def build_user_prompt(python_source: str, existing_module_source: str, python_rel: str) -> str:
    return (
        f"# Source Python file (datasources/{python_rel})\n"
        "This is the file that just changed in 4CAT. The `map_item` function on the "
        "class is the source of truth — your JavaScript translation must produce an "
        "object with the same field names and equivalent values.\n\n"
        f"```python\n{python_source}\n```\n\n"
        "# Existing Zeeschuimer module\n"
        "This module's `capture()` function returns the raw items that will be "
        "passed to `map_item(item)` as `item`. Use it to understand the input shape "
        "and to match the existing code style (ES modules, `export` keyword, etc.).\n\n"
        f"```javascript\n{existing_module_source}\n```\n\n"
        "# Task\n"
        "Produce a JavaScript `map_item(item)` function that mirrors the Python "
        "`map_item`. Re-implement any Python helpers it calls (e.g. `normalize_url_encoding`, "
        "`urlparse`/`parse_qs`, `datetime` formatting) inline in JS — either inside "
        "`map_item_function` or as separate snippets in `helpers_to_add`. If you reference "
        "the `MappedItem` class, list its import in `imports_to_add` (it lives in `../js/lib.js`). "
        "Use `export function map_item(item) { ... }` to match this module's style."
    )


def parse_freetext_response(text: str) -> dict:
    """
    Fallback parser for when structured output is disabled or unreliable.
    Looks for a fenced JS block (the function) and treats remaining text as
    commentary.
    """
    js_match = re.search(r"```(?:js|javascript)\s*\n(.*?)```", text, re.DOTALL)
    map_item_function = js_match.group(1).strip() if js_match else ""
    commentary = re.sub(r"```(?:js|javascript)\s*\n.*?```", "", text, flags=re.DOTALL).strip()
    return {
        "map_item_function": map_item_function,
        "imports_to_add": [],
        "helpers_to_add": [],
        "commentary": commentary,
    }


def validate_translation(translation: dict) -> Optional[str]:
    """
    Returns None if the translation passes basic sanity checks, else a string
    describing what went wrong.
    """
    fn = translation.get("map_item_function", "").strip()
    if not fn:
        return "LLM returned empty map_item_function"
    if not re.search(r"\bmap_item\b", fn):
        return "LLM output does not contain `map_item` identifier"
    if not re.search(r"function\s+map_item|map_item\s*=|map_item\s*:", fn):
        return "LLM output does not declare `map_item` as a function"
    return None


def splice_into_module(existing: str, translation: dict, python_rel: str) -> str:
    """
    Idempotently insert / replace the auto-generated marker blocks in the JS
    module text.

    Raises ValueError if exactly one of (start, end) markers is present —
    that means the file is corrupted or partially hand-edited and we should
    refuse to touch it.
    """
    main_block_body = []
    for helper in translation.get("helpers_to_add", []):
        helper = helper.strip()
        if helper:
            main_block_body.append(helper)
    fn = translation["map_item_function"].strip()
    main_block_body.append(fn)
    main_block = (
        f"{BLOCK_MARKER_START}\n"
        f"// (regenerated from {python_rel})\n"
        + "\n\n".join(main_block_body)
        + f"\n{BLOCK_MARKER_END}\n"
    )

    imports = [imp.strip() for imp in translation.get("imports_to_add", []) if imp.strip()]
    # Drop imports that already appear verbatim outside the marker block.
    existing_outside_block = re.sub(
        re.escape(BLOCK_MARKER_START) + r".*?" + re.escape(BLOCK_MARKER_END) + r"\n?",
        "",
        existing,
        flags=re.DOTALL,
    )
    existing_outside_imports_block = re.sub(
        re.escape(IMPORTS_MARKER_START) + r".*?" + re.escape(IMPORTS_MARKER_END) + r"\n?",
        "",
        existing_outside_block,
        flags=re.DOTALL,
    )
    imports = [imp for imp in imports if imp not in existing_outside_imports_block]

    imports_block = ""
    if imports:
        imports_block = (
            f"{IMPORTS_MARKER_START}\n"
            + "\n".join(imports)
            + f"\n{IMPORTS_MARKER_END}\n"
        )

    updated = existing

    # Replace or insert imports block.
    has_imports_start = IMPORTS_MARKER_START in updated
    has_imports_end = IMPORTS_MARKER_END in updated
    if has_imports_start ^ has_imports_end:
        raise ValueError(
            "Auto-generated imports markers are partially missing in the existing "
            "module — refusing to overwrite. Restore both markers or remove both."
        )
    if has_imports_start and has_imports_end:
        updated = re.sub(
            re.escape(IMPORTS_MARKER_START) + r".*?" + re.escape(IMPORTS_MARKER_END) + r"\n?",
            imports_block,
            updated,
            count=1,
            flags=re.DOTALL,
        )
    elif imports_block:
        # Prepend at top of file.
        if updated and not updated.startswith("\n"):
            updated = imports_block + "\n" + updated
        else:
            updated = imports_block + updated

    # Replace or append main block.
    has_main_start = BLOCK_MARKER_START in updated
    has_main_end = BLOCK_MARKER_END in updated
    if has_main_start ^ has_main_end:
        raise ValueError(
            "Auto-generated map_item markers are partially missing in the existing "
            "module — refusing to overwrite. Restore both markers or remove both."
        )
    if has_main_start and has_main_end:
        updated = re.sub(
            re.escape(BLOCK_MARKER_START) + r".*?" + re.escape(BLOCK_MARKER_END) + r"\n?",
            main_block,
            updated,
            count=1,
            flags=re.DOTALL,
        )
    else:
        if not updated.endswith("\n"):
            updated += "\n"
        updated += "\n" + main_block

    return updated


def translate_one(
    llm: LLMAdapter,
    python_path: Path,
    repo_root: Path,
    zeeschuimer_root: Path,
    use_structured_output: bool,
) -> dict:
    """
    Translate one Python file. Returns a manifest entry dict.
    """
    rel = python_path.relative_to(repo_root).as_posix()
    entry = {
        "python_file": rel,
        "js_file": None,
        "status": "failed",
        "commentary": "",
        "error": None,
    }

    if not is_zeeschuimer_datasource(python_path):
        entry["status"] = "skipped"
        entry["error"] = "not a Zeeschuimer datasource (is_from_zeeschuimer != True)"
        return entry

    js_rel = PLATFORM_MAP.get(rel)
    if not js_rel:
        entry["status"] = "skipped"
        entry["error"] = f"no Zeeschuimer module mapped for {rel}"
        return entry
    entry["js_file"] = js_rel

    js_path = zeeschuimer_root / js_rel
    if not js_path.exists():
        entry["status"] = "skipped"
        entry["error"] = f"Zeeschuimer module {js_rel} does not exist in checkout"
        return entry

    python_source = python_path.read_text(encoding="utf-8")
    existing_module = js_path.read_text(encoding="utf-8")
    user_prompt = build_user_prompt(python_source, existing_module, rel)

    try:
        response = llm.generate_text(user_prompt, system_prompt=SYSTEM_PROMPT)
    except Exception as e:
        entry["error"] = f"LLM call failed: {e}"
        return entry

    if use_structured_output:
        # with_structured_output returns the parsed dict directly.
        if isinstance(response, dict):
            translation = response
        else:
            entry["error"] = (
                f"Expected dict from structured output, got {type(response).__name__}"
            )
            return entry
    else:
        text = getattr(response, "content", str(response))
        translation = parse_freetext_response(text)

    bad = validate_translation(translation)
    if bad:
        entry["error"] = bad
        return entry

    try:
        spliced = splice_into_module(existing_module, translation, rel)
    except ValueError as e:
        entry["error"] = str(e)
        return entry

    js_path.write_text(spliced, encoding="utf-8")
    entry["status"] = "ok"
    entry["commentary"] = translation.get("commentary", "").strip()
    return entry


def main():
    cli = argparse.ArgumentParser(description=__doc__)
    group = cli.add_mutually_exclusive_group(required=True)
    group.add_argument("--files", nargs="+", help="Specific datasource files to translate.")
    group.add_argument(
        "--bootstrap",
        action="store_true",
        help="Translate every Zeeschuimer datasource in the repo.",
    )
    cli.add_argument(
        "--zeeschuimer-checkout",
        required=True,
        type=Path,
        help="Path to a local clone of the Zeeschuimer repo.",
    )
    cli.add_argument(
        "--output-manifest",
        required=True,
        type=Path,
        help="Where to write the JSON manifest of results.",
    )
    cli.add_argument(
        "--model",
        default=os.environ.get("LLM_MODEL", DEFAULT_MODEL),
        help=f"Ollama model to use (default: {DEFAULT_MODEL}, or $LLM_MODEL).",
    )
    cli.add_argument(
        "--no-structured-output",
        action="store_true",
        help="Disable JSON-schema structured output; parse the response as free text.",
    )
    args = cli.parse_args()

    dmi_ollama_key = os.environ.get("DMI_OLLAMA_KEY")
    if not dmi_ollama_key:
        sys.exit("Error: DMI_OLLAMA_KEY environment variable not set.")

    repo_root = Path(__file__).resolve().parent.parent

    if args.bootstrap:
        files = discover_bootstrap_files(repo_root)
        if not files:
            sys.exit("No Zeeschuimer datasources found to bootstrap.")
    else:
        files = [Path(f).resolve() for f in args.files]

    llm = LLMAdapter(
        provider="ollama",
        model=args.model,
        base_url="https://ollama.digitalmethods.net",
        temperature=0.2,
        max_tokens=8192,
        client_kwargs={"headers": {"X-API-KEY": dmi_ollama_key}},
    )

    use_structured_output = not args.no_structured_output
    if use_structured_output:
        try:
            llm.set_structure(LLM_SCHEMA)
        except Exception as e:
            print(
                f"Warning: could not enable structured output ({e}); "
                "falling back to free-text parsing.",
                file=sys.stderr,
            )
            use_structured_output = False

    print(f"Using model: {args.model} (provider: ollama, structured_output: {use_structured_output})")

    entries = []
    for python_path in files:
        print(f"Translating {python_path.relative_to(repo_root).as_posix()}...")
        try:
            entry = translate_one(
                llm,
                python_path,
                repo_root,
                args.zeeschuimer_checkout.resolve(),
                use_structured_output,
            )
        except Exception as e:
            entry = {
                "python_file": str(python_path),
                "js_file": None,
                "status": "failed",
                "commentary": "",
                "error": f"unexpected exception: {e}\n{traceback.format_exc()}",
            }
        entry["model"] = args.model
        entries.append(entry)
        print(f"  -> {entry['status']}" + (f" ({entry['error']})" if entry.get("error") else ""))

    manifest = {
        "model": args.model,
        "provider": "ollama",
        "structured_output": use_structured_output,
        "entries": entries,
    }
    args.output_manifest.parent.mkdir(parents=True, exist_ok=True)
    args.output_manifest.write_text(json.dumps(manifest, indent=2), encoding="utf-8")

    n_ok = sum(1 for e in entries if e["status"] == "ok")
    n_failed = sum(1 for e in entries if e["status"] == "failed")
    n_skipped = sum(1 for e in entries if e["status"] == "skipped")
    print(f"\nDone with model `{args.model}`: {n_ok} ok, {n_failed} failed, {n_skipped} skipped.")
    print(f"Manifest written to {args.output_manifest}")

    if n_ok == 0 and n_failed > 0:
        sys.exit(1)


if __name__ == "__main__":
    main()
